### ISSUE TITLE
Issue template improvement

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-modernization#272]
I have been looking at the SP Usage Docs Project - https://github.com/SharePoint/sp-usage-docs/issues 

When raising an issue they are using multiple issue templates that present as buttons. When submitted the issues are auto-tagged. Just a thought to reduce effort marking issues :-)

**Comment by jansenbe** [comment]
Indeed a nice approach that we can clone, thanks for pointing this out @pkbullock .

**Comment by pkbullock** [comment]
It looks like this is done and can be closed if you are happy to do so.

**Comment by jansenbe** [comment]
yep, closing
