### ISSUE TITLE
Add option to not place image placeholder for missing assets

### ISSUE THREAD

**Issue by ToddKlindt** [pnp/sp-dev-modernization#398]
#### Category

[ ] Bug
[x] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Running 3.16.1912.0 of the PowerShell module
Include a switch to not include an image placeholder in the destination page when the engine can't find an asset and generates a "Asset was not transfered" error. 
And it should be spelled "transferred" in the message.

**Comment by jansenbe** [comment]
@ToddKlindt, that's good feedback and something useful to include.

Typo has been fixed.

**Comment by jansenbe** [comment]
Hey @ToddKlindt ,

I've been looking into this and it's not so easy to implement this as I'll need to either detect "the missing image" case early on and don't push a web part into the transformation process or alternatively drop the web part during transformation.

Can you provide some more context on which source images are not transferable and should be skipped? By default if an image is not transferable we keep the original URL for the target image url.

**Comment by jansenbe** [comment]
Closing as the complexity out weights the needed time investment
