### ISSUE TITLE
Is it possible to map a single field to multiple web parts?

### ISSUE THREAD

**Issue by mbice** [pnp/sp-dev-modernization#450]
#### Category

[ ] Bug
[X] Enhancement

We are trying to map complex content from our classic pages that contain HTML blocks that drive behavior (tabs, accordions, etc). In classic we use JavaScript to apply the behavior, but in modern we would prefer to map these blocks to specialized web parts.

Ideally we could break apart a single content field (e.g. PublishingPageContent) and map to multiple web parts (combination of text and other web parts) on the target. For example, if our PublishingPageContent field contains some text, followed by an HTML snippet, then followed by some additional text we would want to map this to 3 separate web parts on the target (WikiTextPart, some custom web part, then another WikiTextPart).

I've looked at custom functions, but that looks to me only able to transform the value of the field and map directly to a single web part. I need to split the field apart and map to multiple parts.

Any ideas on how this can be done?

Thanks!

**Comment by jansenbe** [comment]
Hey @mbice ,

I did some quick testing and this can be done using a custom function. Below are the steps you need to take:

1. Follow https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing#addons-definition-in-the-page-layout-model to create a new VS project in which you reference the SharePointPnP.Modernization.Framework.dll you're using (e.g. reference from the PS location if you're using PS or pull down the nuget)
2. Write a custom function that takes as input the html content and an indicator of the section you need. Below is very simple sample:

```csharp
public string SplitInput(string input, string sectionNumber)
{
    // Parse the received html content and return the part you need
    return $"Part {sectionNumber}";
}
```
3. Ensure this binary can be found by either copying it to location of the other binaries (e.g. when using PS) or by referencing it via fully qualified path in your page layout file
4. Update your page layout mapping file to plug in the custom function:

```Xml
<PublishingPageTransformation xmlns="http://schemas.dev.office.com/PnP/2019/03/PublishingPageTransformationSchema">
  <AddOns>
    <!-- Assembly can contain either a fully qualified path or just the dll name. In the latter case we depend on .Net assembly resolving to find the assembly -->
     <AddOn Name="Custom" Type="SharePointPnP.Modernization.Framework.SampleAddOn.MyCustomFunctions" Assembly="SharePointPnP.Modernization.Framework.SampleAddOn.dll" />
  </AddOns>
  <PageLayouts>
    <PageLayout Name="XXX" AssociatedContentType="CustomPage1" PageLayoutTemplate="AutoDetect" IncludeVerticalColumn="true" PageHeader="Custom">
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="true">
          <!-- header config -->
      </Header>
      <MetaData ShowPageProperties="true" PagePropertiesRow="1" PagePropertiesColumn="4" PagePropertiesOrder="1">
          <!-- metadate field config -->
      </MetaData>
      <WebParts>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
          <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'1')" />
        </Field>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
          <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'2')" />
        </Field>
          <!-- other field to web part config -->
      </WebParts>
      <WebPartZones>
          <!-- web part zone config -->
      </WebPartZones>
      <FixedWebParts>
          <!-- fixed web part config -->
      </FixedWebParts>    
    </PageLayout>
  </PageLayouts>
</PublishingPageTransformation>

```

Hope this helps, probably the harder part will be the html content splitting. We use AngleSharp as html parsing library: check the TransformPlusSplit method to get some inspiration on how we use AngleSharp: https://github.com/SharePoint/sp-dev-modernization/blob/master/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Transform/WikiHtmlTransformator.cs#L61

Interested in hearing back how things work out.

**Comment by mbice** [comment]
Thanks, this is a great start.

For point #2 I didn't know I could return the web part itself as output of a custom function. So even though the field invoking the function is being mapped to a WikiTextPart it will transform to the part I return in the function, which may be a different kind of part? Will this work for custom parts as well?

Also, given I don't know how much content there will be and how many parts will come out of the parsing, is the idea that I just put a bunch of field mappings in place to account for a really large potential number of parts? E.g.

<WebParts>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
          <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'1')" />
        </Field>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
          <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'2')" />
          
<Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'20')" />
        </Field>
      </WebParts>

Thanks!

**Comment by jansenbe** [comment]
@mbice :

For your first question: yes, this should work with custom parts as well because this function is invoked before the transformation work is done. So imagine that: 
- In "part 2" of the provided html field content there's classic html containing 2 web parts and text and one of these is a custom web part 
- You've updated the webpartmapping.xml file to include a mapping to a new modern version of the custom web part

then the transformation will replace this by a text editor, an OOB modern web part and your custom  modern web part.

For question 2: yes, empty text parts are removed from the page before saving, so adding like 20 parts as 20 mappings should work.

**Comment by mbice** [comment]
Hi @jansenbe 

I think I'm missing something here. Let's say I have the following HTML in PublishingPageContent on my classic page:

```html
<p>some text here</p>
<div class="custom" data-prop1="val1"></div>
<p>more text</p>
```

Now I want to parse that field and split into a WikiTextPart for the first paragraph, a custom web part to replace the middle div, and then another WikiTextPart for the last paragraph. I guess where I'm stuck is that I'm trying to call a split function and map to a WikiTextPart for that middle div. If my custom function returns a string, how do I actually map it to anything other than a WikiTextPart?

```csharp 
public string SplitInput(string input, string sectionNumber)
{
    // Parse the received html content and return the part you need
    // Is there a special format to this string to have it map to a custom web part? Or should I be 
    // returning something other than a string? 
    return $"Part {sectionNumber}";
}
```

Thanks!

**Comment by jansenbe** [comment]
For each split input call there should be a field mapped to a target web part (e.g. WikiTextPart)...you're essentially telling the transformation engine to process the same input field multiple times but by using the SplitInput function you just provide a part of the fields content

**Comment by mbice** [comment]
Ok, but is there a way I can change the target web part dynamically depending on the output of the custom split function? Let's say I have a bunch of field references to PublishingPageContent, and in one of them the Property function determines that it's my custom div, which will map to a custom web part. If I use WikiTextPart as the TargetWebPart then I don't see how it can map to anything other than WikiTextPart...

```xml
<Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
   <!-- Is there any way to change the target web part based on the output of this Function? -->
    <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'2')" />
</Field>
```

Or is the idea that I use groupings of Field references for each split section of the content to account for the possibility of each block of parsed content being one of several web parts? E.g.
```xml
<Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
    <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'1')" />
</Field>
<Field Name="PublishingPageContent" TargetWebPart="<CustomWebPartReference>" Row="1" Column="2">
    <Property Name="JsonControlData" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'1')" />
</Field>

<Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
    <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'2')" />
</Field>
<Field Name="PublishingPageContent" TargetWebPart="<CustomWebPartReference>" Row="1" Column="2">
    <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'2')" />
</Field>

<Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="2">
    <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'3')" />
</Field>
<Field Name="PublishingPageContent" TargetWebPart="<CustomWebPartReference>" Row="1" Column="2">
    <Property Name="Text" Type="string" Functions="Custom.SplitInput({PublishingPageContent},'3')" />
</Field>
<!-- do this a bunch of times to account for multiple possible references of CustomWebPart -->
```

Thanks!

**Comment by jansenbe** [comment]
You can use other web parts as well but it will be static (so your second example). Keep in mind that you need to ensure that you populate all the properties that the other web part needs to correctly configure itself. If you take a look in the webpartmapping.xml file you see properties being defined for a web part, the ones that have a function on their line are typically required to make things work.

**Comment by mbice** [comment]
@jansenbe thanks for all the help. I was able to get this working as desired using the many static mappings approach and a custom parser. Thanks!
