### ISSUE TITLE
PS Term Mapping and KeepPageCreationModification not working

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-modernization#453]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

When running command

```powershell
ConvertTo-PnPClientSidePage -Identity "Quality-Cherry-Cake.aspx" -PublishingPage `
    -TargetConnection $spOnlineConn -Connection $sp13Conn `
    -Overwrite `
    -PageLayoutMapping C:\temp\Demo\custompagelayoutmapping-f3629db3-3e4d-48c4-b904-6fffab6dbb65-quality-cherry-cake.xml `
    -UserMappingFile C:\temp\Demo\usermapping.csv `
    -UrlMappingFile C:\temp\Demo\urlmapping.csv `
    -TermMappingFile C:\temp\Demo\termmapping.csv `
    -PostAsNews `
    -DisablePageComments `
    -KeepPageCreationModificationInformation `
    -LogType File `
    -LogVerbose -LogFolder C:\temp\Demo\
```

you get in the console/file:

15/03/2020 20:41:39  |  **Article page handling**  |  **There was a non critical issue during page update/publish. Returned error message: Object reference not set to an instance of an object.**

**Comment by jansenbe** [comment]
@pkbullock : testing this from spo to spo does not result in an error (see #454), now checking on-prem to spo. Would be good if you could attach a debugger at your side to see where things go wrong and/or share the verbose log of the failed transform

**Comment by jansenbe** [comment]
@pkbullock : no repro so far when testing from sp2013 to SPO

**Comment by pkbullock** [comment]
Argh, sorry wasting time, I double checked this, the source page didn't have the field in the first place for the metadata. Closing.
