### ISSUE TITLE
Show Properties doesnt work when refering to taxonomy field

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-modernization#454]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[X] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

In preparation for an upcoming demo on modernisation tooling, i tried to get the show properties web part feature to work on taxonomy fields. This did not in publishing page transformation from on-prem 2013 to SPO.

This needs some investigation.

See attached mapping file.

[onprem-news-mapping.txt](https://github.com/SharePoint/sp-dev-modernization/files/4347639/onprem-news-mapping.txt)

**Comment by jansenbe** [comment]
Showing tax properties works for me, could it be an issue in your page layout mapping?

**Comment by pkbullock** [comment]
Quite possibly, I have attached the mapping, I haven't used this feature much, and followed the docs, in the txt file do you think there is anything missing?

**Comment by jansenbe** [comment]
Hey @pkbullock, 

I've been testing from SPO to SPO and can't repro the issue. Using below snippet and having term mapping enabled:

```Xml
<Field Name="TaxField1" TargetFieldName="Metadata1" Functions="" ShowInPageProperties="true" />
<Field Name="TaxField2" TargetFieldName="Metadata2" Functions="DefaultTaxonomyFieldValue({TaxField2},'a65537e8-aa27-4b3a-bad6-f0f61f84b9f7|69524923-a5a0-44d1-b5ec-7f7c6d0ec160','true')" ShowInPageProperties="true"/>
<Field Name="Person" TargetFieldName="Person" Functions="" ShowInPageProperties="true"/>
```

This is the resulting properties web part on the created page:

![image](https://user-images.githubusercontent.com/7451219/77400458-7ea81000-6dab-11ea-95a5-eca106b2fe62.png)

**Comment by jansenbe** [comment]
@pkbullock : no repro so far when testing from sp2013 to SPO

**Comment by jansenbe** [comment]
@pkbullock : also note that if a field in the target page is not populated then the web part will not show it...might be that you term mapping results in an empty taxonomy field in the source?

**Comment by pkbullock** [comment]
Found the bug, on line 195 in the publishingpageonpremises.cs class, target field instance is null, I believe the code assumes that the user added a site column, rather than directly on the list.  In your example, are they site columns? 

PublishingPage.cs line 213 will have the same issue.

**Comment by jansenbe** [comment]
Yes, I was using site columns. Think we fixed a similar issue a while ago but seems not for publishing pages then

**Comment by pkbullock** [comment]
Working on a fix now...

**Comment by jansenbe** [comment]
@pkbullock : merged your PR, will be part of the April release.
