### ISSUE TITLE
Question : Is there an option to set the page Thumbnail image independently of the header image?

### ISSUE THREAD

**Issue by MartinHatch** [pnp/sp-dev-modernization#456]
Hopefully a quick one ... 

I know you can set the image in the header fairly easily, but a lot of the pages I'm transforming have BOTH the PublishingPageImage *and* the RollupImage specified (i.e. one for the page header, and another for the thumbnail)

**Comment by pkbullock** [comment]
Yes, in publishing pages page layouts mapping, under meta data you can set the thumbnail field to something other than the header image, something I do quite often, if you add the mapping to the metadata section:

```xml
<Field Name="PublishingPageImage" TargetFieldName="BannerImageUrl" Functions="ToPreviewImageUrl({PublishingPageImage})" />
```
This will give you control over the image to place in the thumbnail.

**Comment by MartinHatch** [comment]
Urgh .. I feel so dumb! Thanks @pkbullock

**Comment by jansenbe** [comment]
Thanks for answering @pkbullock , closing the issue now
