### ISSUE TITLE
Conditional header types?

### ISSUE THREAD

**Issue by mbice** [pnp/sp-dev-modernization#459]
#### Category

[ ] Bug
[x ] Enhancement

Hi,

I'm wondering if it's possible to set the header type conditionally based on the value of a particular field?For example, I'd like to set the Header type to "CutInShape" if PublishingPageImage is populated, otherwise set to NoImage.

```xml
<Header Type="CutInShape|NoImage" Alignment="Left" ShowPublishedDate="true">
    <Field Name="PublishingPageImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingPageImage})" />
    <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions="" />
    <Field Name="PublishingContact" HeaderProperty="Authors" Functions="ToAuthors({PublishingContact})" />
</Header>
```

Any chance there's a way to do this currently?

Thanks!

**Comment by pkbullock** [comment]
Hi @mbice 

I've had similar scenario in the past, to work around I created two mapping files and use PowerShell to read the column and determine which mapping file to use.  

For guidance, I used the following from the script in this manner: https://github.com/pnp/sp-dev-modernization/blob/5aa94c3eb60019b8425d27608013fccbc530e035/Scripts/PageTransformation/Convert-PublishingPages.ps1

Line 104.

Does this help?

This isn't a feature in the tool to work in this way, but we could consider this for enhancement, to support variants of the mapping within one file and to select one.

Paul

**Comment by mbice** [comment]
Hi @pkbullock 

Thanks, that helps. Seems like it would be a worthwhile enhancement, imo, but I should be able to work around it for now.

I had also considered adding tokenization to the mapping file so I could populate properties like Header type in Powershell before passing the mapping file into ConvertTo-PnPClientSidePage. Any chance there's general tokenization capabilities coming to the tool at some point in the near future?

Thanks!

**Comment by pkbullock** [comment]
@mbice we haven't considered this option, I will raise an enhancement to get feedback from @jansenbe Im thinking a mechanism much like the properties option in PnP Provisioning where you can place tokens in the XML file.

**Comment by mbice** [comment]
That sounds great, thanks. I'll close this one off and follow the enhancement you raised for updates.
