### ISSUE TITLE
2019 Modern to SPO Modern mode

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-modernization#460]
#### Category

[ ] Bug
[X] Enhancement

When migrating from SharePoint 2019 modern to SharePoint Online modern, there was some web parts that did not work when using the PnP Provisioning tool e.g. Quick links.

I will reproduce to see if this is a bug, but at the same time, got me wondering as the two platforms drift apart in terms of advancement and code bases whether there will be a need to modernise from 2019 modern.

In the instance with my client, I could not use the PnP provisioning tool when templating modern page in 2019 and applying to SPO, so of the web part config broken in SPO.

**Comment by jansenbe** [comment]
Hi @pkbullock ,
2019 uses the same code path as SPO when it comes to reading classic pages, whereas 2016 and lower use asmx services for some of the data loads...that might be a reason for this failing. Having a clear repro will help.

when doing other tasks besides modernization for SP2019 you should use the 2019 version of PnP PowerShell as there for example are major differences between the modern page API implementations across 2019 and SPO

**Comment by jansenbe** [comment]
@pkbullock : do we still need to do something here or can this be closed?

**Comment by jansenbe** [comment]
Closing this one @pkbullock , feel free to re-open if you still feel it's relevant
