### ISSUE TITLE
Get-PnPListItem :Cannot invoke a method or retrieve a property from a null object. The object returned by the following the call stack is null..

### ISSUE THREAD

**Issue by vonvaclav** [pnp/sp-dev-modernization#462]
Hello

i have issue with migration sharepoint online old site to modern. I use this manual https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-powershell but powershell generate error

Get-PnPListItem :Cannot invoke a method or retrieve a property from a null object. The object returned by the following the call stack is null.. GetList At C:\Users\vacla\OneDrive\Plocha\preklopeni.ps1:18 char:28 + $pagesInSitePagesLibrary = Get-PnPListItem -List "sitepages" + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ + CategoryInfo : WriteError: (:) [Get-PnPListItem], ServerException + FullyQualifiedErrorId : EXCEPTION,SharePointPnP.PowerShell.Commands.Lists.GetListItem

thank you for your help Vaclav

I dont have idea, what i can to do.

Thank you for help

Vaclav

**Comment by jansenbe** [comment]
Which version of PnP PowerShell are you using?
What's the source version of your SharePoint environment (are you migrating from on-prem or from online)?
Can you run Get-PnPException immediately after the failing call and share the outcome?

**Comment by jansenbe** [comment]
Closing per no feedback
