### ISSUE TITLE
Documentation missing term mapping options

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-modernization#463]
In the documentation for cmdlet reference for PnP PowerShell: https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/convertto-pnpclientsidepage?view=sharepoint-ps

The cmdlet is missing the new term mapping cmdlet parameters. I think this page a auto generated from the code, is there an additional task or property attribute needed to show this up in the page. Just learning to some of the related docs as well.

**Comment by jansenbe** [comment]
That's indeed auto generated documentation, seems as there was no refresh done for the March release. Adding @erwinvanhunen for awereness.

**Comment by pkbullock** [comment]
The documentation is updated from latest release.
