### ISSUE TITLE
The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator.

### ISSUE THREAD

**Issue by vikassharmaatl** [pnp/sp-dev-modernization#464]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[X] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Scanner completes successfully

#### Observed Behavior

On executing the scanner the following exception happens:
The attempted operation is prohibited because it exceeds the list view threshold enforced by the administrator.

#### Steps to Reproduce

Executing the scanner using the UI generates the above error.

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Thanks for reporting this @vikassharmaatl , this indeed is an issue that needs to be addressed in the next version of the scanner. As a workaround you can configure your Azure AD application to use full control - that will make the scanner use an alternative code path which avoids the large list scan.

**Comment by vikassharmaatl** [comment]
Thanks!

**Comment by jansenbe** [comment]
Adding @vgurusa for awareness as he logged the same issue

**Comment by jansenbe** [comment]
@vikassharmaatl , @vgurusa, 

The issue has been solved (see https://github.com/pnp/sp-dev-modernization/commit/6f8a061c9ce790895320a3a76f78230c372ccdaf) and will be part of the 2.11 release. If you want earlier access then you can build the dev branch yourselves and use the created exe.

**Comment by vikassharmaatl** [comment]
Thanks Bert!

**Comment by jansenbe** [comment]
Closing this issue since it's been fixed.
