### ISSUE TITLE
LikesCount and LikedBy fields?

### ISSUE THREAD

**Issue by mbice** [pnp/sp-dev-modernization#466]
#### Category

[ ] Bug
[x] Enhancement

Hi,

We use ratings (likes) in classic for up-voting content and ideally we could bring this over in our modernization process. Are there plans to support brining over LikesCount and LikedBy fields? I tried mapping them in my page layout mapping XML and couldn't get anything to move over correctly.

Thanks!

**Comment by pkbullock** [comment]
Hi @mbice 

Is it possible to provide your mapping? I will have a look and see if we can map them.

Paul

**Comment by pkbullock** [comment]
I've done some investigation,  the modern likes and comments doesn't appear to store the information against the list item but another data store.

Each list item has a REST API method to "like" an item but the context is fixed to the current logged on user so import other likes from other users, there does not appear to be an API to support this.  We need a API or CSOM method that would allow us to make the changes to the modernization tooling to support this.

I may need @jansenbe input as he has deeper API knowledge or access to resources backend that I don't.

**Comment by jansenbe** [comment]
@pkbullock is correct, there's no API today for creating likes/comments by a migration tool as we need to be able to set the like/comment author/date when doing a migration. I've a thread ongoing with the feature owner and there's willingness to work on an API, but that will not be a near future deliverable. So for now there's not much that can be done.

**Comment by jansenbe** [comment]
See also #431

**Comment by mbice** [comment]
@jansenbe @pkbullock thanks for looking into this and confirming the current state of things.

**Comment by jansenbe** [comment]
Closing this one per comments added in #431
