### ISSUE TITLE
Enterprise WIKI fails transform from SharePoint 2013

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-modernization#467]
#### Category

[X] Bug
[ ] Enhancement

#### Problem Area

-[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
-[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
-[X] Page Transformation: Error during the use of page transformation from .Net
-[ ] Page Transformation: Page is not looking correct after transformation
-[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Enterprise WIKI transforms from SharePoint 2013 to SharePoint Online.

#### Observed Behavior

Transform falls back to web services and error is generated in the logs:
[Content Transform] Calling Web Services to Extract Web Parts from Page
Error: [Summary] A critical error occurred - transformation did not complete Error: 'spsswc' is an undeclared prefix. Line 6, position 2.

#### Steps to Reproduce

- Enterprise WIKI site in SharePoint 2013
- Transform Home with following commands:

```powershell
Export-PnPClientSidePageMapping `
    -CustomPageLayoutMapping `
    -PublishingPage "Home.aspx" `
    -Folder (Get-Location) `
    -Connection $sp13ConnTeamSite

#onprem13-enterwiki-home.xml
ConvertTo-PnPClientSidePage -Identity "Home.aspx" -PublishingPage `
    -TargetConnection $spOnlineConn -Connection $sp13Conn `
    -Overwrite `
    -PageLayoutMapping "$(Get-Location)\onprem13-enterwiki-home.xml" `
    -LogType Console
```

**Comment by jansenbe** [comment]
Thanks for testing @pkbullock , will you be able to handle this for the May release? I've tentatively assigned this issue to the May release

**Comment by pkbullock** [comment]
Yeap no worries.

**Comment by jansenbe** [comment]
Closing as your pr was merged. Thx @pkbullock
