### ISSUE TITLE
Pages inside the Pages library is redirecting back to "~Site/Pages/Forms/AllItems.aspx"

### ISSUE THREAD

**Issue by InfosysAdmin** [pnp/sp-dev-modernization#469]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ #] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ #] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

After transforming the site to modern, Pages inside the Pages library is redirecting back to "~Site/Pages/Forms/AllItems.aspx". If the library's experience is changed to classic, the pages are working fine

**Comment by pkbullock** [comment]
Are you turning on the modern experience for the pages library for classic publishing sites? Or you transforming the pages with the transformation tooling?

**Comment by InfosysAdmin** [comment]
Transformed the pages with transformation tool

**Comment by jansenbe** [comment]
Do you have embedded script on the source page that causes this? Can you try to manually make a new page in the sitepages library and see if that works?

**Comment by InfosysAdmin** [comment]
Pages without embedded script is also getting the same issue. Issue reported in Publishing pages library alone. Not in sitepages.

**Comment by jansenbe** [comment]
What do you mean with "issue reported in publishing pages library alone"? Page transformation is creating pages in the SitePages library, it will not update anything in the publishing pages library

**Comment by InfosysAdmin** [comment]
Yea. After converting the Classic site to Modern(Disabling classic experience feature), this issue is observed

**Comment by jansenbe** [comment]
? You cannot do an in-place modernization of publishing pages. I still don't understand the full context of your issue, sorry

**Comment by InfosysAdmin** [comment]
The pages inside the publishing pages library are left undisturbed.. Just after upgrading the site to modern and library experience to modern(Done using the feature), Pages inside the Publishing Pages library is redirecting back to "/Pages/Forms/AllItems.aspx

**Comment by jansenbe** [comment]
Yes, think that's expected if you have a page named default.aspx...can rename that page and see if it fixes things

**Comment by jansenbe** [comment]
Still confused here: a library with classic publishing pages will never coexist with a sitepages library in the same site...that's an unsupported scenario. When you modernize publishing pages you should create the resulting modern pages in another site, typically a communication site. At that point there's no need to force the site with the classic publishing pages to be modern in my view

**Comment by jansenbe** [comment]
Will be closing this one, if you feel this is a bug in page transformation then please drop me an email on bjansen@microsoft.com so that we can setup a meeting to discuss.
