### ISSUE TITLE
Search Webparts- Unavailable in Modern Pages

### ISSUE THREAD

**Issue by InfosysAdmin** [pnp/sp-dev-modernization#470]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ *] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[* ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

Search webparts such as SearchBoxScriptWebPart, SearchNavigationWebPart, RefinementScriptWebPart are all unavailable in modern, preventing us to transform the classic page to Modern. Any replacement available? If unavailable, when it is expected to be available?

**Comment by pkbullock** [comment]
Hi @InfosysAdmin there is a community project for these web parts, for creating custom modern search experiences, this is a great resource: 

https://github.com/microsoft-search/pnp-modern-search 
and demo on YouTube: https://youtu.be/SG3ngNXGUX8

**Comment by InfosysAdmin** [comment]
Any out of the box webpart available as replacement for search?

**Comment by pkbullock** [comment]
There are no first-party (OOB) web parts in modern that work the same way as the classic search center.

**Comment by jansenbe** [comment]
@InfosysAdmin : like mentioned by @pkbullock there are no OOB modern search web parts, the referenced community project is what we currently recommend. Since we don't have OOB web parts we also don't have a mapping for them in page transformation --> this mapping will be very complex, if possible at all. For now I would recommend manually configuring the open source search web parts on the pages that need it.

**Comment by jansenbe** [comment]
Closing this issue as this not something page transformation can solve at this point.
