### ISSUE TITLE
Force map headings (h2, h3, etc)

### ISSUE THREAD

**Issue by mbice** [pnp/sp-dev-modernization#471]
#### Category

[ ] Bug
[x] Enhancement

Hi,

Is there currently a way to define how the headings are mapped (e.g. h1, h2, h3, etc)? The problem we are facing now is that through governance we've trained authors to not use "Heading 1" in classic because it conflicts with the page title. So our top level headings on all of our pages are H2. Since "heading 1" in modern is now actually an H2, the engine demotes the heading number of the content when it is transformed (so an H2 in classic becomes an H3 in modern) and all of our pages are missing top level headings. Ideally we would like to be able to specify that H2 is considered a top level heading for content and have it translate to an H2 on the modern site page as well.

Thoughts? Is this currently possible?

Thanks!

**Comment by jansenbe** [comment]
@mbice : today this is not possible OOB, but you can consider creating a custom build of page transformation. The needed changes are simple and need to be done in https://github.com/pnp/sp-dev-modernization/blob/dev/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Transform/HtmlTransformator.cs#L104. 

The complexity will be in building both the modernization library as PnP PowerShell

**Comment by mbice** [comment]
@jansenbe thanks for the clarification. I tried pre-transforming the content to increase the heading counts (e.g. H2 is converted to H1, H3 to H2, etc) before it goes through full transformation, at which point it gets moved back down to where it was when it started. This way an H2, which is our top level heading in all our content, stays an H2 after transformation. Bit of a workaround, but seems to work well enough at this point.

Thanks!
