### ISSUE TITLE
Removing Column Name Whitespaces 

### ISSUE THREAD

**Issue by vgurusa** [pnp/sp-dev-modernization#472]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[X] Enhancement

If you can ensure all the columns generated within output files doesn’t have whitespaces that would be great!
•	ModernizationWorkflowScanResults.csv
•	ModernizationListScanResults.csv
•	ModernizationBlogWebScanResults.csv
•	ModerniationInfoPathScanResults.csv
•	ModernizationBlogPageScanResults.Csv
•	Errors.csv

**Comment by jansenbe** [comment]
Hey @vgurusa ,

Can you explain why the space in the column title is causing issues? If I wrap the column titles in double quotes in the CSV files then imports typically should work. Would that fix your issue?

**Comment by vgurusa** [comment]
We are storing all the column names as PSObject properties which is the format our tool understands and if there are spaces I have to check for them and replace it for every single row on the CSV files. This would be more efficient, if I don't have to do the check and replace for all the rows in each file.

**Comment by jansenbe** [comment]
Can't you include a "replace space with nothing" logic in your code creates the PSObject when you import the CSV? Below example imports columns having a space in their name and creates objects without:

```Powershell
$values = import-csv .\ModernizationSiteScanResults.csv -Delimiter ';' | foreach-object {  [PSCustomObject]@{ 'SiteUrl' = $_.'Site Collection Url' ; 'Url' = $_.'Site Url' } } 
```

**Comment by vgurusa** [comment]
This could work but the problem, I see with this option though is it becomes very specific to each file whichever has whitespace columns and doesn't. The way we do it is keeping it very generic (for all CSV files) irrespective of whatever the column name we just add the respective column name and values into the PSObject property. 

If this is going to be a big change on your end don't bother about it.

**Comment by jansenbe** [comment]
I've done some more checking and doing the change is a lot of work, can potentially break customers (we've an option to consolidate earlier generated CSV files into a single report), including updating all docs...hence I'm not in favor of doing this.

An alternative approach for your issue would be to write a PS script that updates the first line of each CSV file and removes the spaces from the column titles before you import them

**Comment by vgurusa** [comment]
I definitely like the option to replace the first line of the CSV file. I think that will keep things really simple on my end and yours as well. Appreciate the quick update Bert!

**Comment by jansenbe** [comment]
Ok, let's then close this issue.
