### ISSUE TITLE
Irrelevant Title column values shown in Project Tasks list in New Experience

### ISSUE THREAD

**Issue by InfosysAdmin** [pnp/sp-dev-modernization#473]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[*] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[*] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

After Changing the Project Tasks List's experience to modern, Title Column is showing Irrelevant junk values.

**Comment by jansenbe** [comment]
This is not a page transformation question but more a question on the OOB behavior when you switch a web part to show as modern. Was in the classic rendering the title column also shown? If not then please hide it in the current view.

In general classic Task web parts (and classic calendar) do not show in modern at all or have a limited experience, I've no experience with the Microsoft Project task web parts however, seems like something you create a bug for via your support channel.

**Comment by InfosysAdmin** [comment]
The title values are rendered perfectly in Classic view

**Comment by jansenbe** [comment]
Then please open a bug via Microsoft support. This is not related to page transformation, hence I'm going to close this issue, hope you understand.
