### ISSUE TITLE
Use Stock Images during Transformation

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-modernization#476]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

New function to allow a SharePoint stock image to be used on transformation pages.  The idea that pages can be enriched during transform with stock images.

**Comment by jansenbe** [comment]
Wouldn't this not already be possible today by creating a hard coded reference to the needed stock image in your page layout mapping file? Wondering how you would see this being more dynamic?

**Comment by pkbullock** [comment]
I hadn't considered that, so use a page/web part to load the file into the site before transform and then static reference. 

I started to look at how this service works e.g. https://hubblecontent.osi.office.net/contentsvc/api/pivots?filter=pivotNames/any(p:%20p%20eq%20%27Stock%20Images%27)&search=Golf&top=1&skip=0

The search param on the above URL.

Then load the image e.g. https://cdn.hubblecontent.osi.office.net/m365content/publish/5052b1ec-5916-4fa3-8b84-ee4f089238ed/153753583.jpg based on the path of the result above. 

Couldn't figure out yet how the UI the filename saved to site assets is constructed from this above and may reference another source.  

Your solution is simpler, as the user could use the UI to find the file.

**Comment by pkbullock** [comment]
Lets close this, think we settled not to enhance this area.
