### ISSUE TITLE
Option to include list columns when exporting Page Layout mapping

### ISSUE THREAD

**Issue by pkbullock** [pnp/sp-dev-modernization#477]
#### Category

[ ] Bug
[X] Enhancement

#### Expected or Desired Behavior

When generating a page mapping file using the PS "Export-PnPClientSidePageMapping" cmdlet, on selecting a specific file, the analyzer doesn't take into consideration the list columns on the page itself just the layout file, when generating the metadata section.

I've seen a reference to this issue and comment on this that started me thinking about whether to include this:

https://github.com/pnp/sp-dev-modernization/issues/465#issuecomment-616820671

**Comment by jansenbe** [comment]
Hey @pkbullock ,
I'm not against adding this feature, but don't you think that most folks using publishing pages use proper content types and have their columns defined on the content type?

**Comment by pkbullock** [comment]
I am tempted to close this one. I don't see any demand for this.
