### ISSUE TITLE
Document library template-Not working properly after Modern UI Upgrade

### ISSUE THREAD

**Issue by InfosysAdmin** [pnp/sp-dev-modernization#480]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[* ] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[* ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

After the library's experienced changed to Modern, the documents which are created in A4 format using the template in a document library are now opening in Letter format

**Comment by jansenbe** [comment]
Hey @InfosysAdmin ,

This is not related to page transformation. When you say "open in letter" are you talking about opening in the desktop version of Word?

**Comment by InfosysAdmin** [comment]
No, Opening in Browser. i.e Word Online

**Comment by InfosysAdmin** [comment]
The document library has document templates where the word document size format is "A4".(Please find the screenshot). We already uploaded documents in A4 format when the site was classic. After upgrading the site, the library experience is changed to modern. Now, when we open the same documents, the size formatting is changed to "Letter". Please help us in understanding whether the upgrade of the site will affect the existing document size, orientation etc.

![ScreenShot1](https://user-images.githubusercontent.com/57442089/82630908-bc8dad00-9c11-11ea-990f-4460840c5e7c.png)

**Comment by jansenbe** [comment]
Might be an issue in Word Online, would recommend opening up support case for this. It's for sure not related to the modernization tools as we're not touching this area at all. I'll close the case now, given it's something that need to be handled via support channels.
