### ISSUE TITLE
Index was out of range. Must be non-negative and less than the size of the collection.

### ISSUE THREAD

**Issue by TroyHostetter** [pnp/sp-dev-modernization#482]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category
Bug

#### Problem Area
Page Transformation:  Error during use

#### Observed Behavior
Error thrown:  Index was out of range. Must be non-negative and less than the size of the collection

#### Steps to Reproduce
Transformation from a SP2013 Home.aspx OnPrem to SPO .. page type is WikiContent

#### Submission Guidelines
Get-PnPStorageEntity output: WARNING: Tenant app catalog is not available on this tenant.
Get-PnPTenantServicePrincipalPermissionGrants : Insufficient privileges to complete the operation.

StackTrace
_Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.LastColumnOrder(Int32 row, Int32 col)
   at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
   at SharePointPnP.Modernization.Framework.Transform.PageTransformator.Transform(PageTransformationInformation pageTransformationInformation)_ 

SharePointPnP.Modernization.Framework.dll version 1.0.2005.0
SharePointPnPPowerShellOnline version 3.21.2005.1

**Comment by jansenbe** [comment]
@TroyHostetter 

Can you please do the following:
- Run the transformation with logging enabled and provide the output md file
- For the page that fails, I would need to inspect the wiki html which you can get into the clipboard using below PnP PowerShell script

```PowerShell
# Check the id of your home.aspx page first
$p = Get-PnPListItem -List sitepages -Id 1
# copy contents into clipboard
$p.FieldValues["WikiField"] | clip
```

**Comment by jansenbe** [comment]
Hey @TroyHostetter , did you manage to fix your problem? If so feel free to close the issue, if not please provide the requested information so we can have a look. Thx.

**Comment by jansenbe** [comment]
Closing this one since there's no response. Don't hesitate to create a new issue with the requested details in case you're facing this issue again.

**Comment by Varinder-netizen** [comment]
Hi Troy, Its Varinder here
 Were you able to resolve this?
