### ISSUE TITLE
Client Page conversion issue

### ISSUE THREAD

**Issue by KHaranadh** [pnp/sp-dev-modernization#486]
Hi Team,

After conversion to client side page using ConvertTo-PnPClientSidePage we are getting below error and we are unable edit or publish any new changes.

Observations:
- Page converted Successfully 
- But unable do any modifications 
- Source Page Admin and Destination Admin are different

ERROR:
**REST error Error with code -2146232832, Microsoft.SharePoint.SPException due to Inner-Message: The specified user i:0#.f|membership|SHAREPOINT\system could not be found. Exception-Message: [HTTP]:500 - [CorrelationId]:af595a9f-a00f-2000-436e-201d0bc18791 [Version]:16.0.0.20127 at Error: Inner-Message: The specified user i:0#.f|membership|SHAREPOINT\system could not be found.**

**Comment by jansenbe** [comment]
@KHaranadh : can you please share the version of PnP PowerShell you're using and the PowerShell cmdline you're using? When running `connect-pnponline` add the -verbose flag to see the version being used. If it's not a recent version then please upgrade to the latest version first.

Are you transforming from on-premises to online or from online to online? Are you using account mapping?

**Comment by KHaranadh** [comment]
Hi Jansebe,

we are using 3.21.2002.2 PnP version.
My requirement to connect convert onpremise SP-2013 classic Pages and Site pages to Modern Communication site pages.
Please Advice me the steps I need to follow.

**Comment by jansenbe** [comment]
Hey @KHaranadh ,

Please ensure you're running the latest version of PnP PowerShell, we just released version 3.22.2006.0

Can you show how you are using the `ConvertTo-PnPClientSidePage` cmdlet? I want to see if you are using account mapping or not

**Comment by KHaranadh** [comment]
Hi Jansenbe,

Installed latest PnP version.

Please find the below cmdlet....
ConvertTo-PnPClientSidePage -Identity tester.aspx -Library Pages -PublishingPage  -Overwrite -TargetWebUrl https://xxxxx.sharepoint.com/sites/global

Complete Error:

REST error Error with code -2146232832, Microsoft.SharePoint.SPException due to Inner-Message: The specified user i:0#.f|membership|SHAREPOINT\system could not be found. Exception-Message: [HTTP]:500 - [CorrelationId]:b4ab5a9f-805d-2000-6c3b-cc71eab62c22 [Version]:16.0.0.20127 at Error: Inner-Message: The specified user i:0#.f|membership|SHAREPOINT\system could not be found. Exception-Message: [HTTP]:500 - [CorrelationId]:b4ab5a9f-805d-2000-6c3b-cc71eab62c22 [Version]:16.0.0.20127 at new t (https://spoprod-a.akamaihd.net/files/sp-client/sp-pages-assembly_en-us_97e207b387935aeeabe001b8810cfbd2.js:1:425609) at Function.e._getOdataRestApiError (https://spoprod-a.akamaihd.net/files/sp-client/chunk.sp-pages-statemanager_en-us_8565533d5032d58b8247.js:1:21444) at https://spoprod-a.akamaihd.net/files/sp-client/chunk.sp-pages-statemanager_en-us_8565533d5032d58b8247.js:1:22267}

**Comment by jansenbe** [comment]
Can you try with user mapping (see https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-usermapping):

- create a usermapping.csv file with below contents (adjust the SPO account):

```
sharepoint\system,xxx@xxx.onmicrosoft.com
```

Use this mapping file during transformation by specifying it using the `-UserMappingFile` parameter of the `ConvertTo-PnPClientSidePage` cmdlet and let me know if that resolves the issue.

**Comment by KHaranadh** [comment]
Sure Jansenbe, I will try this.. Thanks for the update

**Comment by KHaranadh** [comment]
Thanks for the solution Jansenbe, -UserMappingFile option working
