### ISSUE TITLE
Mapping custom webparts with the Use of Webpartmapping xml

### ISSUE THREAD

**Issue by AllanSamuelT** [pnp/sp-dev-modernization#490]
Hi Guys,

This is more inline to a query than an Issue. Need your guidance.

I am currently trying to map a content editor from Source to a react community script editor taken from [Here](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor).

The content editor contains a content under Edit Source - HTML button to simply trigger an alert.

The page transformation script is used as per the example and The Script editor SPFx app is compiled and is added as an app in the target site. 

`PageTransformationInformation pti = new PageTransformationInformation(page)
{
    // If target page exists, then overwrite it
    Overwrite = true,
};
pti.MappingProperties["UseCommunityScriptEditor"] = "true";
pageTransformator.Transform(pti);`

Post transformation, I am able to see a text webpart saying - Content editor contains script and could not be loaded.

I'm assuming that I must be missing to change something in the webpart mapping XML. As of now it is in its vanilla form.

`<Mapping Name="NonASPXUseCommunityScriptEditor" Default="false">
            <ClientSideWebPart Type="Custom" ControlId="3a328f0a-99c4-4b28-95ab-fe0847f657a3" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&#125;,&quot;imageSources&quot;&#58;&#123;&#125;,&quot;links&quot;&#58;&#123;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;1.0&quot;,&quot;properties&quot;&#58;&#123;&quot;script&quot;&#58;&quot;{FileContentsEncoded}&quot;,&quot;title&quot;&#58;&quot;{Title}&quot;,&quot;removePadding&quot;&#58;false,&quot;spPageContextInfo&quot;&#58;false&#125;&#125;"/>
          </Mapping>
          <Mapping Name="ContentUseCommunityScriptEditor" Default="false">
            <ClientSideWebPart Type="Custom" ControlId="3a328f0a-99c4-4b28-95ab-fe0847f657a3" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&#125;,&quot;imageSources&quot;&#58;&#123;&#125;,&quot;links&quot;&#58;&#123;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;1.0&quot;,&quot;properties&quot;&#58;&#123;&quot;script&quot;&#58;&quot;{Script}&quot;,&quot;title&quot;&#58;&quot;{Title}&quot;,&quot;removePadding&quot;&#58;false,&quot;spPageContextInfo&quot;&#58;false&#125;&#125;"/>
          </Mapping>`

Kindly help me in sorting this out.

Thanks

**Comment by AllanSamuelT** [comment]
Breakthrough, I was able to read from the Content Editor and pass the content onto a Script Editor.

Currently I am trying to read a file in the ContentLink of the Content editor and this seems to be a Real issue. I am getting the below errors every time there is a file added in the contentlink a simple html or javascript.

`Built-in Function  |  An error occurred in LoadContentFromFile function    at Microsoft.SharePoint.Client.ClientRequest.ProcessResponseStream(Stream responseStream)

   at Microsoft.SharePoint.Client.ClientRequest.ProcessResponse()

   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplementation>d__7.MoveNext()

--- End of stack trace from previous location where exception was thrown ---

   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)

   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)

   at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(ClientRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)

   at SharePointPnP.Modernization.Framework.Functions.BuiltIn.LoadContentFromFile(String contentLink)`

**Comment by jansenbe** [comment]
Hi @AllanSamuelT ,

I assume you've seen the docs around using the script editor web part as transformation target: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-webparts#enabling-the-use-of-the-community-script-editor-web-part-to-be-used-during-transformation

Can you show the content link you're using? It must be a server relative url (so starting from /sites/...). The error you get is thrown in below code block:

```csharp
try
                {
                    // Content editor does allow a web part on a sub web to point to a file in the rootweb...Pointing to files outside of the current site collection is not allowed
                    Uri hostUri = new Uri(this.clientContext.Web.GetUrl());

                    // Find the web url hosting the content file
                    var webUrlResult = Web.GetWebUrlFromPageUrl(this.clientContext, $"{hostUri.Scheme}://{hostUri.DnsSafeHost}{contentLink}");
                    this.clientContext.ExecuteQueryRetry();

                    using (var cc = this.clientContext.Clone(webUrlResult.Value))
                    {
                        return cc.Web.GetFileAsString(contentLink);
                    }
                }
                catch (Exception ex)
                {
                    LogError(LogStrings.Error_LoadContentFromFile, LogStrings.Heading_BuiltInFunctions, ex);
                    return "";
                }
```

**Comment by AllanSamuelT** [comment]
Hello Jansen @jansenbe,

Yup, I've read the documentation.

I am attempting to transfer the content (contains only HTML, no JavaScript) onto a Text webpart on the Canvas(Preferably) or a community script editor. I can ignore the source html file once the content is transferred onto the page canvas.

The URL is the ContentLink goes like "/Sites/<Subsite>/<Subsite>/Documents/htmlfile.htm".

How should I proceed with this ?

**Comment by AllanSamuelT** [comment]
I ran the code block in my environment and found that the line `return cc.Web.GetFileAsString(contentLink);` - is returning File Not Found.

The url being passed is a server relative url. "/Sites/Subsite/Subsite/Documents/paintext.txt" - passed a text file.

**Comment by jansenbe** [comment]
If the content contains no html it will end up as a text part, we'll only use the script editor if the content contains JS and if you've enabled using the script editor. Seems like in your case something goes wrong with reading the file the content editor points to...Would you be able to debug this by pulling down the source code? Source code lives here: https://github.com/pnp/sp-dev-modernization/tree/master/Tools/SharePoint.Modernization. Function that fails is https://github.com/pnp/sp-dev-modernization/blob/master/Tools/SharePoint.Modernization/SharePointPnP.Modernization.Framework/Functions/BuiltIn.cs#L1006. 

I also assume you did not update the web part mapping files and are using the built in one?

**Comment by jansenbe** [comment]
Hi @AllanSamuelT , 

Did you manage to debug this? If you're OK then we can close this issue?

**Comment by jansenbe** [comment]
Closing this issue as there was no feedback for the last 3 weeks. If this is still an issue please open a new issue and cross reference this one. Thanks.
