### ISSUE TITLE
need to change hardcoded URLs

### ISSUE THREAD

**Issue by junterpfe** [pnp/sp-dev-modernization#494]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[ ] Bug
[X ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[X ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

I would expect the tool to work on GCC/GCCH/DoD

#### Observed Behavior

When trying to reach a national cloud auth fails due to the wrong endpoints (.com vs .us)

#### Steps to Reproduce

Try to connect to a GCCH tenant using any of the supported auth methods, it fails. i can work with someone to test if needed (junter@microsoft.com)

**Comment by jansenbe** [comment]
Hi @junterpfe ,

Can you provide me with the error's you're getting?

**Comment by junterpfe** [comment]
[A screenshot of a cell phone  Description automatically generated]
Getting a 401 unauthorized because it is trying to hit the .com address for auth instead of the .us address

https://docs.microsoft.com/en-us/office365/enterprise/office-365-u-s-government-gcc-high-endpoints

covers the differences.

John Unterseher MCSE MCSA MCT
Microsoft Customer Engineer
813.260.0162
[A blue Rectangle with the Microsoft Logo and the words "DSE Microsoft 365"]

If you have any feedback about my work, please let either me or my manager, Kris Levin-Snow, know at Kris.LevinSnow@microsoft.com<mailto:Kris.LevinSnow@microsoft.com>

**Comment by junterpfe** [comment]
![21C13BE9-EA2D-47C7-9964-BEFDF9B47CA3](https://user-images.githubusercontent.com/47872678/87485383-ac3cf180-c606-11ea-9335-d38e11ac78b1.jpeg)

**Comment by jansenbe** [comment]
@junterpfe : I send you a dev build via Teams chat, would be good if you could give that one a try and let me know

**Comment by jansenbe** [comment]
@junterpfe : the next release will support other cloud environments (like GCCH) when Azure AD App-Only (Cert authentication) is chosen. Other auth options will still not work for GCCH.

**Comment by jansenbe** [comment]
version 2.13 is out, closing this issue
