### ISSUE TITLE
Default URL rewriting seemingly occurs twice if target site URL string contains source site collection URL

### ISSUE THREAD

**Issue by DmitryVorobyov** [pnp/sp-dev-modernization#495]
Thank you for reporting an issue or suggesting an enhancement. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Category

[x] Bug
[ ] Enhancement

#### Problem Area

[ ] Page Transformation: Error during the setup/use of the Page Transformation UI solution (did you check our [troubleshooting guide](https://github.com/SharePoint/sp-dev-modernization/blob/dev/Solutions/PageTransformationUI/docs/troubleshootingguide.md)?)
[x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

- After cross-site transformation, a link on a page is expected to be transformed as follows (via default URL rewriting): 

_<tenant.sharepoint.com>/sites/**myportalNEW**/Documents/filename.ext_

#### Observed Behavior

- After the cross-site transformation, the link is transformed as follows (via default URL rewriting): 

_<tenant.sharepoint.com>/sites/**myportalNEWNEW**/Documents/filename.ext_

#### Steps to Reproduce

Set up the following cross-site page transformation:

- Source classic site URL: _<tenant.sharepoint.com>/sites/myportal/subsite1_
- The classic page being transformed contains a link, pointing to: _<tenant.sharepoint.com>/sites/myportal/subsite1/Documents/filename.ext_ 
- Target site URL: _<tenant.sharepoint.com>/sites/myportalNEW_

**Notes:**

Page transformation engine version used:   1.0.2006.0
No errors or exceptions in the log file

**Comment by pkbullock** [comment]
Hi @DmitryVorobyov 

Are you able to provide the command you used to run the transform? please include the parameters, I am at this moment unable to reproduce. So I ran as a test, Publishing Page from a subsite with a web part, summary links and inline text within the Publishing HTML content - this worked for me. 

So from: **https://tenant.sharepoint.com/sites/PnPSauce/en/Documents/Employee%20Handbook.docx**
to https://tenant.sharepoint.com/sites/PnPKatchup/Documents/Employee%20Handbook.docx

Is this scenario similar or correct to the one you have described?

**Comment by pkbullock** [comment]
I have managed to reproduce the issue, after re-reading the issue, investigating the bug fix.

**Comment by jansenbe** [comment]
Thanks for the fix @pkbullock !

@DmitryVorobyov : this fix will be included in the August release (which is still about 4 weeks out).

**Comment by DmitryVorobyov** [comment]
Thank you, @pkbullock, appreciate the help!

**Comment by jansenbe** [comment]
Change has been merged, so I'll close the issue now
