### ISSUE TITLE
Create a version that works with vanity url's.  This errors out if your Office365 tenant uses vanity url's.

### ISSUE THREAD

**Issue by saiafrad** [pnp/sp-dev-modernization#501]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by jansenbe** [comment]
Hi @saiafrad , are you talking about the modernization scanner or about page transformation? Both do work with vanity url's, so please provide more details on what goes wrong.

**Comment by saiafrad** [comment]
Below is the thread I had with Microsoft from a ticket that I submitted.  As you can see I have tried many ways to get this to work in our environment but it has not been successful.  Please let me know how I should move forward with this issue.


________________________________
From: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>
Sent: Tuesday, May 19, 2020 4:59 PM
To: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls


Hi Frank,



Just wanted to follow-up on this.  Did you get this to work?  Basically we need Azure App Credentials no matter what it seems.



Thanks,

Savoeurn Va (Vern)

Su-Wed 9:30am to 8:30PM CST (UTC -6:00)

Microsoft SharePoint Technologies

Sr. Support Escalation Engineer | savoeva@microsoft.com<mailto:savoeva@microsoft.com> | Phone: 701-281-7547

Manager: Jim Cumming | Jimcu@microsoft.com<mailto:Jimcu@microsoft.com> |



From: Savoeurn Va (VERN)
Sent: Tuesday, May 12, 2020 1:22 PM
To: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



Hi Frank,



I called the number listed in the case a moment ago but got voicemail.

I think we’ll have to fall back to setting up an Azure App Credentials for this tool.  I was hoping it skip that code block with the CSV file.



I highlighted the section that it is, basically what the stack says is read next line on CSV then read the Azure Auth Token.



[cid:image001.png@01D65B50.6C618510]



When I use your CSV file as input, I get Access Denied message as I would expect:

[cid:image002.png@01D65B50.6C618510]





Your also going to need to open the issue here: https://github.com/pnp/sp-dev-modernization/issues<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpnp%2Fsp-dev-modernization%2Fissues&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878644831&sdata=p6SHzPBuwcaa7MzCtgixzsg8W18p1peBeRHVUQFy3iI%3D&reserved=0>.   As support for this product is actually through that location, not directly with SPO support itself.



Thanks,

Savoeurn Va (Vern)

Su-Wed 9:30am to 8:30PM CST (UTC -6:00)

Microsoft SharePoint Technologies

Sr. Support Escalation Engineer | savoeva@microsoft.com<mailto:savoeva@microsoft.com> | Phone: 701-281-7547

Manager: Jim Cumming | Jimcu@microsoft.com<mailto:Jimcu@microsoft.com> |



From: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>
Sent: Tuesday, May 12, 2020 1:07 PM
To: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: [EXTERNAL] RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



I tried it with 10,000, 5000, 1000, 20, and 10 and they all failed with the same message.  I also tried it by using just one of our vanity url’s (https://share.philips.com<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fshare.philips.com%2F&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878654827&sdata=a8G7l9YhantxXIMxiZyn7X0a2cs7XGsummwg5aXZEN8%3D&reserved=0>) and it still gave the same error message.





[cid:image003.png@01D65B50.6C618510]





Frank Saia
Regional Operations Manager Collaboration AMEC

I&O Personal IT AMEC

Philips IT Global Services

3000 Minuteman Rd. Andover Ma. 01810

Cell Phone: 603-781-8270, Alt. Cell Phone: 603-343-6117, Email: frank.saia@philips.com<mailto:frank.saia@philips.com>





[cid:image004.gif@01D65B50.6C618510]



From: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>
Sent: Tuesday, May 12, 2020 1:44 PM
To: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



Hi Frank,



I checked file and I don’t see any spaces on it and I also recreated the contents using Excel to create a CSV file.  What’s possibly happening is the list is to large when it does the scanning operation against the CSV.  What happens if you cut this down in chunks?  For instance try using ½ of the sites or a 1/4 at a time to test?



Thanks,

Savoeurn Va (Vern)

Su-Wed 9:30am to 8:30PM CST (UTC -6:00)

Microsoft SharePoint Technologies

Sr. Support Escalation Engineer | savoeva@microsoft.com<mailto:savoeva@microsoft.com> | Phone: 701-281-7547

Manager: Jim Cumming | Jimcu@microsoft.com<mailto:Jimcu@microsoft.com> |



From: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>
Sent: Tuesday, May 12, 2020 11:43 AM
To: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: [EXTERNAL] RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls









Frank Saia
Regional Operations Manager Collaboration AMEC

I&O Personal IT AMEC

Philips IT Global Services

3000 Minuteman Rd. Andover Ma. 01810

Cell Phone: 603-781-8270, Alt. Cell Phone: 603-343-6117, Email: frank.saia@philips.com<mailto:frank.saia@philips.com>





[cid:image004.gif@01D65B50.6C618510]



From: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>
Sent: Tuesday, May 12, 2020 10:49 AM
To: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



Hi Frank,



Based off the error, it is reading the CSV file, but when it moved on to next item into the CSV, the error says that input was blank.



Can you send me the CSV file you used?  I’d like to inspect it.



Thanks,

Savoeurn Va (Vern)

Su-Wed 9:30am to 8:30PM CST (UTC -6:00)

Microsoft SharePoint Technologies

Sr. Support Escalation Engineer | savoeva@microsoft.com<mailto:savoeva@microsoft.com> | Phone: 701-281-7547

Manager: Jim Cumming | Jimcu@microsoft.com<mailto:Jimcu@microsoft.com> |



From: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>
Sent: Tuesday, May 12, 2020 8:20 AM
To: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: [EXTERNAL] RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



I tried by using user name and password and using a csv file of all sites in SharePoint and all options for the scan and got the following error message.



[cid:image005.png@01D65B50.6C618510]





Frank Saia
Regional Operations Manager Collaboration AMEC

I&O Personal IT AMEC

Philips IT Global Services

3000 Minuteman Rd. Andover Ma. 01810

Cell Phone: 603-781-8270, Alt. Cell Phone: 603-343-6117, Email: frank.saia@philips.com<mailto:frank.saia@philips.com>





[cid:image004.gif@01D65B50.6C618510]



-----Original Appointment-----
From: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>
Sent: Monday, May 11, 2020 3:26 PM
To: Saia, Frank; Microsoft Premier Support
Subject: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls
When: Monday, May 11, 2020 2:30 PM-3:00 PM (UTC-06:00) Central Time (US & Canada).
Where: Microsoft Teams Meeting





________________________________________________________________________________

You're invited to join a Microsoft Teams meeting.

Join online now<https://teams.microsoft.com/l/meetup-join/19%3ameeting_NDkyYmVkMWMtZDJhYS00ZGY0LThjZWYtYjdlOGRmMTViNjY1%40thread.v2/0?context=%7b%22Tid%22%3a%2272f988bf-86f1-41af-91ab-2d7cd011db47%22%2c%22Oid%22%3a%22e3cfb733-78ee-4dbd-b264-dd7b22cb3eb7%22%7d>

Video conferencing, screen sharing, and more.

Or join by phone (audio only)

+1 773-917-4061,,331322318#<tel:+17739174061,,331322318#>   United States, Chicago

(866) 641-7188,,331322318#<tel:8666417188,,331322318#>   (Toll-free)

Phone Conference ID: 331 322 318#

Find a local number<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdialin.teams.microsoft.com%2F48b4c613-cc67-4825-8175-29628d9715e5%3Fid%3D331322318&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878664822&sdata=8eIyTnSFvM4XR5THcHxMcW94Np2dXjOhtPSHEcFPIVs%3D&reserved=0> | Reset PIN<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fmysettings.lync.com%2Fpstnconferencing&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878664822&sdata=SlbJE6e1kRtdFvVJcOBZG6tFjTVFUW5ncHJvYcv%2BHSc%3D&reserved=0>

Help<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Faka.ms%2FJoinTeamsMeeting&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878674821&sdata=xCOprSE0ZMepezlNqufmKzgEfVagkyxZisox5ef08yI%3D&reserved=0> | Meeting options<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fteams.microsoft.com%2FmeetingOptions%2F%3ForganizerId%3De3cfb733-78ee-4dbd-b264-dd7b22cb3eb7%26tenantId%3D72f988bf-86f1-41af-91ab-2d7cd011db47%26threadId%3D19_meeting_NDkyYmVkMWMtZDJhYS00ZGY0LThjZWYtYjdlOGRmMTViNjY1%40thread.v2%26messageId%3D0%26language%3Den-US&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878684814&sdata=BLtCJEK2%2FG8vkj2HlIl4LHmp9d%2FSlg6Lr4Ez8zdjZBs%3D&reserved=0>

________________________________________________________________________________





_____________________________________________
From: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>
Sent: Monday, May 11, 2020 2:25 PM
To: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: [EXTERNAL] Re: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



Can you call me over Teams in about 5 minutes?



From: "Savoeurn Va (VERN)" <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>
Date: Monday, May 11, 2020 at 3:23 PM
To: Saia Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>, Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



Are you free for quick call?



Thanks,

Savoeurn Va (Vern)

Su-Wed 9:30am to 8:30PM CST (UTC -6:00)

Microsoft SharePoint Technologies

Sr. Support Escalation Engineer | savoeva@microsoft.com<mailto:savoeva@microsoft.com> | Phone: 701-281-7547

Manager: Jim Cumming | Jimcu@microsoft.com<mailto:Jimcu@microsoft.com> |



From: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>
Sent: Monday, May 11, 2020 2:23 PM
To: Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>; Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: [EXTERNAL] Re: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



So are you saying that I would have to create an app in Azure in order to run this?



From: "Savoeurn Va (VERN)" <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>
Date: Monday, May 11, 2020 at 3:21 PM
To: Saia Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>, Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Subject: RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



Hi Frank,



Yes, that is correct.   The reason for this is the need to enumerate the site collections to build the scan list.  Based off the error stack, itself to do enumeration, requires App Authentication.



Thanks,

Savoeurn Va (Vern)

Su-Wed 9:30am to 8:30PM CST (UTC -6:00)

Microsoft SharePoint Technologies

Sr. Support Escalation Engineer | savoeva@microsoft.com<mailto:savoeva@microsoft.com> | Phone: 701-281-7547

Manager: Jim Cumming | Jimcu@microsoft.com<mailto:Jimcu@microsoft.com> |



From: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>
Sent: Monday, May 11, 2020 1:31 PM
To: Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>; Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>
Subject: [EXTERNAL] RE: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



Not sure what you are saying, we have over 70k sites, I cannot list every site that we have.



Is this the option you are saying that I would need to use?



[cid:image006.png@01D65B50.6C618510]





Frank Saia
Regional Operations Manager Collaboration AMEC

I&O Personal IT AMEC

Philips IT Global Services

3000 Minuteman Rd. Andover Ma. 01810

Cell Phone: 603-781-8270, Alt. Cell Phone: 603-343-6117, Email: frank.saia@philips.com<mailto:frank.saia@philips.com>





[cid:image007.gif@01D65B50.6C618510]



From: Microsoft Premier Support <o365pmer@microsoft.com<mailto:o365pmer@microsoft.com>>
Sent: Monday, May 11, 2020 1:30 PM
To: Saia, Frank <frank.saia@philips.com<mailto:frank.saia@philips.com>>; Savoeurn Va (VERN) <savoeva@microsoft.com<mailto:savoeva@microsoft.com>>
Subject: [Case #:19948522] SharePoint modernization tool doesn't work with vanity urls



## Please type your reply above this line ##

________________________________



Title: SharePoint modernization tool doesn't work with vanity urls

[Image removed by sender. Microsoft Corporation]

Your request (19948522) has been updated. To add additional comments, please reply to this email.

________________________________



Savoeurn (Microsoft)

Monday, May 11, 2020 5:29 PM GMT

Hello Frank,



I am the engineer on this case.  I looked at the screen shots provided and pulled the tool down myself. Also as a preface, wanted to make sure that you have noticed this page in regards to support for this tool: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fsharepoint%2Fdev%2Ftransform%2Fmodernize-scanner&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878684814&sdata=GQ2Jo70vNpxfj%2BCQ2jkZIBtPT4f%2FJ%2Fo32uqVuAtGR20%3D&reserved=0>



Support is technically done via: https://github.com/pnp/sp-dev-modernization/issues<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fpnp%2Fsp-dev-modernization%2Fissues&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878694811&sdata=LGzGULYqQ6qCdXzwEXhTUGZnpGxMV10mH7SOceGZ6V0%3D&reserved=0>



However, with that said I ran test myself using similar settings and can see the problem you are facing.  The crux the problem lies with this stack:



Unhandled Exception: System.Exception: No user specified that can be used for site enumeration. Use the SetEnumeration... method to provide credentials as app-only does not work with search

   at OfficeDevPnP.Core.Framework.TimerJobs.TimerJob.get_EnumerationUser()

   at OfficeDevPnP.Core.Framework.TimerJobs.TimerJob.ResolveSite(String site, List`1 resolvedSites)

   at OfficeDevPnP.Core.Framework.TimerJobs.TimerJob.ResolveAddedSites(List`1 addedSites)

   at SharePoint.Modernization.Scanner.Core.ModernizationScanJob.ResolveAddedSites(List`1 addedSites) in C:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\ModernizationScanJob.cs:line 374

   at OfficeDevPnP.Core.Framework.TimerJobs.TimerJob.Run()

   at SharePoint.Modernization.Scanner.Core.ScanJob.Execute() in C:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\ScanJob.cs:line 203

   at SharePoint.Modernization.Scanner.Core.ModernizationScanJob.Execute() in C:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\ModernizationScanJob.cs:line 495

   at SharePoint.Modernization.Scanner.Program.Main(String[] args)





The key part is the first line:



Unhandled Exception: System.Exception: No user specified that can be used for site enumeration. Use the SetEnumeration... method to provide credentials as app-only does not work with search



What this indicates is that we are doing a site collection scan to determine what the site collections are, it needs:  " app-only" credentials.



So if we go back to the screen shots you provided.  We can see the entry of https://share.philips.com/*<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fshare.philips.com%2F*&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878704806&sdata=1P5JDWzs9SAzWRe7c%2FTnWzJ0qeJ4xXFrcOKAe9hy%2FmU%3D&reserved=0>

If we go back a step on the tools GUI, it notes that if you need to scan more than a few URL's, use "App-Only Models".



So if we were to enter in:

https://share.philips.com/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fshare.philips.com%2F*&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878704806&sdata=1P5JDWzs9SAzWRe7c%2FTnWzJ0qeJ4xXFrcOKAe9hy%2FmU%3D&reserved=0>sites/site1

https://share.philips.com/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fshare.philips.com%2F*&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878714801&sdata=Ms6Az9EkJLeV8hVa12bQPolG8R6QHWHJXiSPlAT%2FpG8%3D&reserved=0>sites/site2

https://share.philips.com/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fshare.philips.com%2F*&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878724795&sdata=%2BdaV6u9ERrJ3W6nbz5hOhP41kLJtNW9BPEHhTKddHws%3D&reserved=0>sites/site3



That should work.



If you want to use wildcard, then you need to use the one of the Azure AD App Only auths.  The GUI itself also notes that as well.



Thanks,

Savoeurn Va (Vern)

Su-Wed 9:30am to 8:30PM CST (UTC -6:00)

Microsoft SharePoint Technologies

Sr. Support Escalation Engineer | savoeva@microsoft.com<mailto:savoeva@microsoft.com> | Phone: 701-281-7547

Manager: Jim Cumming | Jimcu@microsoft.com<mailto:Jimcu@microsoft.com> |

Premier Service & Support: 1-800-936-3100 | Premier Online: https://premier.microsoft.com/<https://eur01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fpremier.microsoft.com%2F&data=02%7C01%7C%7Cd5e864953ff649c7c2f608d80d74dd66%7C1a407a2d76754d178692b3ac285306e4%7C0%7C0%7C637274142878724795&sdata=kjPXVJ5ITqehYdQoKR58ng8OebdcMCSF%2FXp2OYzt2WQ%3D&reserved=0>



Tracking ID: b0d787ae-75af-49ee-88b6-7da96e6cd05a



________________________________

The information contained in this message may be confidential and legally protected under applicable law. The message is intended solely for the addressee(s). If you are not the intended recipient, you are hereby notified that any use, forwarding, dissemination, or reproduction of this message is strictly prohibited and may be unlawful. If you are not the intended recipient, please contact the sender by return e-mail and destroy all copies of the original message.



Frank Saia
Regional Operations Manager Collaboration AMEC
I&O Personal IT AMEC
Philips IT Global Services
3000 Minuteman Rd. Andover Ma. 01810
Cell Phone: 603-781-8270, Alt. Cell Phone: 603-343-6117, Email: frank.saia@philips.com<mailto:frank.saia@philips.com>


[cid:image004.gif@01D65B50.6C618510]

**Comment by jansenbe** [comment]
Hi @saiafrad,  
So it's about the scanner and the scanner does work with vanity URL's. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq#im-running-sharepoint-with-vanity-urls-sharepoint-online-dedicated-is-this-different for information on how to scan tenants with vanity url's. If you want to use the wizard (so double clicking on the .exe) then ensure you specify the url's you want to scan as a wildcard url + specify your tenant admin site as shown in below screenshot:
![image](https://user-images.githubusercontent.com/7451219/87706371-adeded00-c79f-11ea-951d-ca3e06304692.png)

**Comment by jansenbe** [comment]
Hey @saiafrad ,

Did you manage to get the scan to run?

**Comment by jansenbe** [comment]
Closing per no feedback for a long time
