### ISSUE TITLE
[BUG] Workflow action counts are 0 and actions empty

### ISSUE THREAD

**Issue by ekdegerman** [pnp/sp-dev-modernization#503]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[x] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

According to the documentation, the output for classic workflows should list information about the workflow configuration, such as how many and which actions are used as well as their compatibility with flow. We would like to see this info to get a clearer picture of the complexity involved in replacing the 2010 workflows that will stop working in November.

#### Observed Behavior

When I run the scanner (version 2.12.0.0), it seems the fields related to actions are always 0 or empty, resulting in -1 as the value for Flow upgradability. See example below from my sandbox tenant that has only one OOB 2010 workflow. The result is the same for all workflows identified in our production tenant as well, though, regardless of whether or not they are OOB. Is this a known error or am I missing something?
![image](https://user-images.githubusercontent.com/56835119/87672631-8e40cf80-c773-11ea-81ad-22cff3a013cd.png)

#### Steps to Reproduce

Run the tool using an AAD app principal having the following permissions assigned. Scan the full tenant, select Classic Workflow Usage and keep everything else as default. 
![image](https://user-images.githubusercontent.com/56835119/87673231-82094200-c774-11ea-94aa-bc9d29265ef4.png)

**Comment by jansenbe** [comment]
@ekdegerman : the fact that you see the workflow listed means the permissions should be sufficient. Is this a custom workflow or an OOB one?

**Comment by ekdegerman** [comment]
Thanks for the clarification @jansenbe! I think that pretty much answers my question. The example above was an OOB one that I set up just to see if I could repeat it across tenants. I didn't see any documented difference between the two, so I figured I could just use one of the ones already installed and not have to bother with SP Designer. We had just three workflows listed as not being OOB in our tenant, of which only two had any subscription. Those also don't list any actions, though. The google translation of two of the names make them sound suspiciously like they could be the same collect feedback and collect signatures workflows that are available out of the box, though they differ in the last three digits of the GUID. The third one is definitely custom, but just set up as a test and not something we will have to migrate. For your info, its setup is shown in the second screen shot below.
![image](https://user-images.githubusercontent.com/56835119/87765150-c0a40880-c817-11ea-9ca1-b4addaac9457.png)
![image](https://user-images.githubusercontent.com/56835119/87768047-dc111280-c81b-11ea-917f-f8980ac7f70c.png)

**Comment by jansenbe** [comment]
@ekdegerman :
I'm prepping a new scanner version that will be able to analyze additional workflows: the ones living the root site's wfpub library can now also be scanned whereas previously only workflow files living in the workflow library were scanned. That hopefully will give you some better results.

**Comment by jansenbe** [comment]
@ekdegerman : can you try scanner version 2.14 and see if that fixes things for you?

**Comment by ekdegerman** [comment]
Thanks! I've started the detailed version now. I'll let you know once it completes.

**Comment by ToddKlindt** [comment]
With the 2.14 scanner I'm getting custom workflows that are showing 0 Action Count and -1 Flow upgradibility. With the 2.12 scanner they showed correctly. 
![image](https://user-images.githubusercontent.com/2659747/88323389-c4d49800-cce7-11ea-8107-d7915d61785d.png)

A week ago with the 2.12 I got this:
![image](https://user-images.githubusercontent.com/2659747/88323679-39a7d200-cce8-11ea-9022-704f354ac31c.png)
I haven't changed the workflows between the two scans. But scans were run with the same command line arguements.

**Comment by jansenbe** [comment]
@ToddKlindt : version 2.14 introduced a new mode "WorkflowWithDetailsOnly", the previous "WorkflowOnly" mode now does not do any analysis at all. This is done for large customers to speed up a first inventory of workflows. With that inventory one can make a CSV file and feed the scanner with a list of workflow sites to scan in detail via the "WorkflowWithDetailsOnly" option.

**Comment by ToddKlindt** [comment]
Thanks, Jan. Sorry for not RTFMing. I'll try it with that new switch.

**Comment by ekdegerman** [comment]
Hmmm, my detailed run from the GUI still has the same result on 2.14...

**Comment by jansenbe** [comment]
@ekdegerman : catching up on things after my vacation. Is this still a concern for you or can I close this issue?

**Comment by jansenbe** [comment]
I'll be closing this issue, just released version 2.16 which does have an improved 2010 XOML file analyzer. If you're still not able to get the needed workflow actions listed and the workflow is not marked as OOB workflow then please open a new issue.
