### ISSUE TITLE
[FEATURE]

### ISSUE THREAD

**Issue by sush315** [pnp/sp-dev-modernization#504]
**Is your feature request related to a problem? Please describe.**
yes . Sharepoint Modernization tool. 
https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner

**Describe the solution you'd like**
We are facing issues after running the setup . It immediately stop saying "The application has stopped working"
We are running it in our Office 365 enviroment using global admin credentials

**Describe alternatives you've considered**
We would like to run the tool using any of the authendication methods.

**Additional context**

**Comment by jansenbe** [comment]
Hi @sush315 ,

Can you provide more details on the what error you're getting? It seems as if you're providing invalid input to the scan and therefore it fails...

**Comment by sush315** [comment]
Hi,

We are following the instructions provided in the below link.
https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner

We are just downloading the setup and then running it 

using the option of Authenticate via credentials, We are providing global admin credentials for that.

Please confirm if we are missing out some steps as this is a new tool and we are using first time. Attaching the screen shot of the error.

**Comment by jansenbe** [comment]
@sush315 : I don't see any screenshot? If you open a command prompt and launch the scanner.exe from there you still get the UI, but once an error happens it should stay visible in the command prompt window. Without error information there's not much I can do

**Comment by sush315** [comment]
hi,

We tried the command prompt option . Please find screen shot attached. 
[Error File.docx](https://github.com/pnp/sp-dev-modernization/files/4971996/Error.File.docx)
[Error File.docx](https://github.com/pnp/sp-dev-modernization/files/4971999/Error.File.docx)

**Comment by jansenbe** [comment]
I assume you're scanning SharePoint Online...the scanner does not work for SharePoint On-premises.

Second thing: the scanner requires the .Net 4.6.1 framework or higher to be installed. Can you cross check what versions are installed on your computer?

What input are you providing in the wizard? Please check https://aka.ms/sharepoint/modernization/scanner to learn more about how to use the scanner

**Comment by sush315** [comment]
We have the correct .Net installed and we are using Authenticate via credentials, We are providing global admin credentials.

Is there a way we can have a screen sharing session so that you can take a look at the issue we are facing.

**Comment by jansenbe** [comment]
Please make screenshots of each page of the wizard and send those...I'm currently OOF but will try to see what I can do

**Comment by sush315** [comment]
<img width="377" alt="Capture1" src="https://user-images.githubusercontent.com/36332122/89181216-dbfd6a80-d5b0-11ea-86c7-84972dc295a4.PNG">
<img width="387" alt="Capture2" src="https://user-images.githubusercontent.com/36332122/89181324-16670780-d5b1-11ea-9b9d-8de285eade8d.PNG">
<img width="423" alt="Capture3" src="https://user-images.githubusercontent.com/36332122/89181485-7cec2580-d5b1-11ea-86e7-d952f5188b0b.PNG">
<img width="449" alt="Capture4" src="https://user-images.githubusercontent.com/36332122/89181556-a2792f00-d5b1-11ea-83de-141ee5ea3dc7.PNG">
<img width="456" alt="Capture6" src="https://user-images.githubusercontent.com/36332122/89181647-cccaec80-d5b1-11ea-8bb4-4ab700379d27.PNG">

**Comment by sush315** [comment]
Please find all the screen shots. Please provide resolution as the earliest as we are looking forward to migration and need the reports on priority

**Comment by jansenbe** [comment]
When you enter the tenant name you only need to specify the name, you can leave out https://. So in your case tenant name needs to be entered as **bd1-admin**

**Comment by sush315** [comment]
Yes that is what we are doing.

**Comment by jansenbe** [comment]
No, your screenshot shows you've entered the https:// in front of the tenant name, that's not needed

**Comment by sush315** [comment]
We have tested that we are only entering bd1-admin in the middle box. The https:// is pre fixed in first box and greyed out cannot be removed or changed.

**Comment by jansenbe** [comment]
Please test with scanning a single site and see if that helps...

**Comment by sush315** [comment]
<img width="462" alt="Capture_new" src="https://user-images.githubusercontent.com/36332122/89561184-c2b92000-d835-11ea-9f86-3df4cc7c6acc.PNG">


we tried with single URL . still same issue.

**Comment by jansenbe** [comment]
Can you confirm the used account can access the site collection being scanned? The account should be site collection admin.

Plan B is trying with app-only (which is anyhow the recommended approach for scanning a complete tenant). Please configure Azure AD app-only and use that.

**Comment by sush315** [comment]
Yes the account has full access.

We need the steps to configure that. Can you please setup a remote session
with us as it's getting delayed now.

**Comment by jansenbe** [comment]
see https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner#step-2-preparing-for-a-scan

**Comment by sush315** [comment]
Do we need Azure admin console to run it.

Please provide us how to install it .

**Comment by jansenbe** [comment]
The steps to properly configure Azure AD app-only require admin access to Azure AD. Please work with your admins to configure that. If you are tenant admin yourself you can follow the instructions in the documentation I shared earlier on: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner#step-2-preparing-for-a-scan

**Comment by sush315** [comment]
We are unable to execute the below command 
Initialize-PnPPowerShellAuthentication -ApplicationName ModernizationScannerApp -Tenant contoso.onmicrosoft.com -Scopes "SPO.Sites.FullControl.All","MSGraph.Group.Read.All"  -OutPath c:\temp -CertificatePassword (ConvertTo-SecureString -String "password" -AsPlainText -Force)

Please let us know which console should we use to run this commaand. We are using sharepointonline managment shell. 
We have used 

Connect-pnpservices
connect-sposervices

Still it fails with error Initialize-PnPPowerShellAuthentication is not a recognized command.

**Comment by sush315** [comment]
Hi ,

We are not getting any response on this issue as already informed its an urgent issue as we are looking as big migration.

Just wanted to inform you that we have maanged to resolve the previous issue but now while running the below command we are getting error exactly after entering the "Tenant " parameter.
<img width="633" alt="Capture-Tenanterror" src="https://user-images.githubusercontent.com/36332122/90266092-21534f00-de71-11ea-8142-9fb3721fdcf4.PNG">

**Comment by jansenbe** [comment]
Seems there are too many things getting mixed up...please contact me at bjansen@microsoft.com for a Teams session to help you get the scanner running. Please ensure you've tenant admin credentials available before the call. I'll close this issue as we're following this up via email.
