### ISSUE TITLE
Custom AddOn with all modernization tool functionalities

### ISSUE THREAD

**Issue by albegut** [pnp/sp-dev-modernization#507]
**Is your feature request related to a problem? Please describe.**
It´s not posible to do all the AddOn functions that a modernization needs it without the soruce client context and the modernization functionalities as the url rewrite, log and assets transfer.

**Describe the solution you'd like**
Add a Xml tag in the webpart mapping file to indicates the modernization tool that the custom AddOn will use the same constructor as BuiltIn class in order to use all the functionalities.

**Describe alternatives you've considered**

**Additional context**
The current AddOns that the user can create only have the target context. If we can add a constructor in the custom AddOn like the one use in the BuiltIn class we could use the source context, the target context and all of the modernization tool functionalities, for example:

1. Log to insert custom messages into the md files
2. UrlTransformator to rewrite webparts url properties
3. UserTransformator
4. AssetTransfer

I change the code and It works perfectly

**Comment by pkbullock** [comment]
Are you able to submit a PR for the code changes?

**Comment by jansenbe** [comment]
@albegut : that indeed would be useful additional to the AddOn concept. Are you willing to create a PR to share your changes?

**Comment by albegut** [comment]
@pkbullock @jansenbe Sorry, I was on holidays. I've just done the PR #516

**Comment by jansenbe** [comment]
@albegut : super news, thanks for sharing your improvements!

**Comment by jansenbe** [comment]
Closing the issue now that I've merged #516 . Thanks again @albegut for sharing this with us!
