### ISSUE TITLE
Set new Home pages after modernization

### ISSUE THREAD

**Issue by albegut** [pnp/sp-dev-modernization#508]
**Is your feature request related to a problem? Please describe.**
Actually the modernization tool is not setting new modernizated page as home page

**Describe the solution you'd like**
Param to indicate the tool to update the home page.

**Describe alternatives you've considered**

**Additional context**
The modernization between on premise and online (not tested other cases) is not setting the modernizated home page as the new home page in SharePoint Online. It would be useful to get a param option to indicates the tool if we want to replace the SharePoint Online home page with the new one.

**Comment by pkbullock** [comment]
Hi @albegut, 

this can be set using PnP PowerShell easily with the Set-PnPHomePage cmdlet.
Reference: [https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnphomepage?view=sharepoint-ps](https://docs.microsoft.com/en-us/powershell/module/sharepoint-pnp/set-pnphomepage?view=sharepoint-ps)

**Comment by jansenbe** [comment]
Thanks for the spot on answer @pkbullock .

@albegut : sorry for the late reply (vacation)...I'm closing this issue as the answer given by Paul does what you need.
