### ISSUE TITLE
[BUG] Unable to scan with csv file from command line

### ISSUE THREAD

**Issue by SVG4365** [pnp/sp-dev-modernization#509]
#### Problem Area
[X ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

I'm using the command line to perform a scan on a batch of sites in a csv file. 
SharePoint.Modernization.Scanner.exe -i 12345678-abcd-abcd-abcd-123456789012 -z xyz.onmicrosoft.com -f xyz.pfx -x NotTheP@ss -t xyz -m WorkflowWithDetailsOnly -v sites.csv

#### Observed Behavior

The scanner initiates a complete tenant scan as if no csv file was specified.

#### Steps to Reproduce

	- Start the scan from the ui with the csv file specified. No Problem
	- Start the scan from the command line pointing to an inexisting csv file. Error: Failed to find csv file with urls. Please check file path provided. 
	- Start the scan from the command line pointing to a csv file. Full tenant scan starts.

Reproduced and confirmed by Microsoft. (version 2.15.0.0)

**Comment by jansenbe** [comment]
@SVG4365 
You need to drop the -t when you scope the scan via a CSV file

**Comment by SVG4365** [comment]
@jansenbe 
Confirmed, Thank you!
