### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by manjunath-bk** [pnp/sp-dev-modernization#510]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

Modernization Scanner: The remote server returned an error: (403) Forbidden...

#### Expected or Desired Behavior

When we select Azure AD App / Azure ACS App only and provide valid data, the tool is getting crashed with remote server returned an error: (403) Forbidden.

#### Observed Behavior
Below Error:
Problem Event Name:    CLR20r3   Problem Signature 01:    SharePoint.Modernization.Scanner   Problem Signature 02:    2.15.0.0   Problem Signature 03:    5f1acab0   Problem Signature 04:    System   Problem Signature 05:    4.7.3451.0   Problem Signature 06:    5d37b695   Problem Signature 07:    a20   Problem Signature 08:    20   Problem Signature 09:    System.Net.WebException   OS Version:    6.3.9600.2.0.0.400.8   Locale ID:    1033   Additional Information 1:    5e40   Additional Information 2:    5e40d992053b7e523b52d496a2baf5f8   Additional Information 3:    5bdf   Additional Information 4:    5bdfe1fd9c0c46e4bd2dec52ca3615c7
Read our privacy statement online:   http://go.microsoft.com/fwlink/?linkid=280262
If the online privacy statement is not available, please read our privacy statement offline:   C:\Windows\system32\en-US\erofflps.txt

Error Detailed:
Launching wizard... ===================================================== Scanning is starting...7/27/2020 10:03:11 AM =====================================================
Unhandled Exception: System.Net.WebException: The remote server returned an erro r: (403) Forbidden.    at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)    at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchron ization) --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot ification(Task task)    at Microsoft.SharePoint.Client.SPWebRequestExecutor.<ExecuteAsync>d__0.MoveNe xt() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot ification(Task task)    at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryToServerAsync>d__6. MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot ification(Task task)    at Microsoft.SharePoint.Client.ClientRequest.<ExecuteQueryAsync>d__0.MoveNext () --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot ification(Task task)    at Microsoft.SharePoint.Client.ClientRuntimeContext.<ExecuteQueryAsync>d__0.M oveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot ification(Task task)    at Microsoft.SharePoint.Client.ClientContext.<ExecuteQueryAsync>d__4.MoveNext () --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot ification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()    at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplement ation>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at Microsoft.SharePoint.Client.ClientContextExtensions.<ExecuteQueryImplement ation>d__7.MoveNext() --- End of stack trace from previous location where exception was thrown ---    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNot ification(Task task)    at System.Runtime.CompilerServices.TaskAwaiter.GetResult()    at Microsoft.SharePoint.Client.ClientContextExtensions.ExecuteQueryRetry(Clie ntRuntimeContext clientContext, Int32 retryCount, Int32 delay, String userAgent)
   at Microsoft.SharePoint.Client.TenantExtensions.GetSiteCollections(Tenant ten ant, Int32 startIndex, Int32 endIndex, Boolean includeDetail, Boolean includeOD4 BSites)    at OfficeDevPnP.Core.Framework.TimerJobs.Utilities.SiteEnumeration.FillSitesV iaTenantAPI(Tenant tenant, Boolean excludeOD4B)    at OfficeDevPnP.Core.Framework.TimerJobs.Utilities.SiteEnumeration.ResolveSit e(Tenant tenant, String siteWildCard, List`1 resolvedSites, Boolean excludeOD4B)
   at OfficeDevPnP.Core.Framework.TimerJobs.TimerJob.ResolveSite(String site, Li st`1 resolvedSites)    at OfficeDevPnP.Core.Framework.TimerJobs.TimerJob.ResolveAddedSites(List`1 ad dedSites)    at SharePoint.Modernization.Scanner.Core.ModernizationScanJob.ResolveAddedSit es(List`1 addedSites) in D:\github\sp-dev-modernization\Tools\SharePoint.Moderni zation\SharePointPnP.Modernization.Scanner.Core\ModernizationScanJob.cs:line 377
   at OfficeDevPnP.Core.Framework.TimerJobs.TimerJob.Run()    at SharePoint.Modernization.Scanner.Core.ScanJob.Execute() in D:\github\sp-de v-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scann er.Core\ScanJob.cs:line 231    at SharePoint.Modernization.Scanner.Core.ModernizationScanJob.Execute() in D: \github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modern ization.Scanner.Core\ModernizationScanJob.cs:line 524    at SharePoint.Modernization.Scanner.Program.Main(String[] args)

#### Steps to Reproduce

Run the tool under select Azure AD app / Azure ACS App only type of authentication.

**Comment by jansenbe** [comment]
Did you do a full tenant scan or just a scan of some site collections? Can you try with scanning a single site collection and see if the error persists? Error indicates access denied, did you grant the needed permissions to the app principal (see https://aka.ms/sharepoint/modernization/scanner)?

Having more insights how you've configured the scan will help

**Comment by manjunath-bk** [comment]
Hi Bert,

i tried also on specific site but no luck, getting failed with the same
error.
Let us know if we can connect and review.

**Comment by jansenbe** [comment]
Please take a fiddler trace when the scanner runs and send that to bjansen@microsoft.com, that will help with identifying the issue. Still suspecting either a wrongly configured app-only principal or bad input in the wizard.

**Comment by jansenbe** [comment]
Closing this issue as there was no feedback for the last 2 weeks. If this still is a problem then please do what I've proposed in the previous comment. Thanks for your understanding.

**Comment by manjunath-bk** [comment]
Hi Bert,

I regret for the delay in responding, got stuck with other priorities.

Anyways we are not getting any logs/trace on fiddler.
When we run this tool with fiddler open we are getting below socket
exception error.
[image: image.jpeg]
Can we have quick teams call so you can extract required information.
