### ISSUE TITLE
[BUG] Scanner goes Not working every time. SPO environment is relatively small and doing Classic Workflow detection since they will be retired soon.

### ISSUE THREAD

**Issue by bzielke24** [pnp/sp-dev-modernization#512]
#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[x ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Expecting the scan to kick off and run.

#### Observed Behavior

Scanning tool goes Not working. Does not produce an error code.

#### Steps to Reproduce

Running the Scanner produces this each time, on 2012 R2 and Win 10.

**Comment by jansenbe** [comment]
Please open a cmd prompt and launch the scanner executable from the prompt, this will show the error in in the cmd prompt. Also please provide the settings you've entered in the scanner

**Comment by jansenbe** [comment]
Closing this issue as there was no feedback for the last 2 weeks. If this still is a problem then please create a new issue and do what I've proposed in the previous comment. Thanks for your understanding.
