### ISSUE TITLE
[BUG] SharePoint Modernization Scanner - v2.15.0.0 - Crashing/Disconnecting during scan of large amounts of sites (> 40 000)

### ISSUE THREAD

**Issue by JulienValentin78** [pnp/sp-dev-modernization#513]
SharePoint Modernization Scanner - v 2.15.0.0 
Running with Azure ACS App crashing/disconnecting during scan of large amounts of sites on a tenant (>40 000 Sites)
Purpose is to assess to find only SharePoint 2010/2013 workflows

Past two days, scanner tool is running on system and still is under progress. 
Below are the issues which we are facing while running this tool:

- Initially when we started the scanner tool it ran for 6 hours and output file is not created under required folder because tool is disconnected before scanning all sites
- Yesterday we started scanning again at 12: 30 PM IST & till 9:45 PM IST only 7602 out of 45339 sites are scanned
- System just lock to keep the scanning process active
- Even we lock the system or we keep the system on sleep mode the scanner process stops and it will resume where it is left once system ON
- Current scanning processed 8757 of 45339 site collections (19%)

Issue, the command prompt getting disappeared after scanning few sites and generating the errors.
We are getting above error message on the screen multiple time and session getting disconnected

![Untitled](https://user-images.githubusercontent.com/51909546/89533644-068b3580-d7f4-11ea-923a-ecae077d37b2.png)

**Comment by jansenbe** [comment]
For such a large amount of sites to scan it's better to split the sites to scan in multiple batches. Also best to ensure you follow the performance guidance lines described here: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq#whats-the-impact-of-running-a-scan-and-how-do-i-get-the-best-performance. To run a scan for a batch of sites you can use a CSV input file as described here: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner#scan-a-list-of-site-collections-defined-in-a-csv-file

**Comment by jansenbe** [comment]
Also to get the error information it's best to open a command prompt (powershell or cmd) and then launch the scanner executable from there. When the scanner errors out the error will stay visible in the command prompt.

**Comment by jansenbe** [comment]
Closing per no additional positive/negative feedback on the 2.15 changes
