### ISSUE TITLE
Errors scanning for Workflows

### ISSUE THREAD

**Issue by sidgdocs** [pnp/sp-dev-modernization#514]
We are using Modernization Scanner to scan for Workflows. During the scan we are seeing lot of errors (please see below) being logged  in in Errors.csv. We are using "Authenticate via Azure AD app-only". Tried with both Command line and GUI. The same errors being logged. Please suggest if any additional configuration is required to perform the scan.

Error-1:
"The property or field 'Url' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.","MainSiteLoop","at Microsoft.SharePoint.Client.ClientObject.CheckUninitializedProperty(String propName)   at Microsoft.SharePoint.Client.Site.get_Url()   at Microsoft.SharePoint.Client.SiteExtensions.<GetAllSubSites>d__0.MoveNext() in D:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Framework\Extensions\SiteExtensions.cs:line 22   at SharePoint.Modernization.Scanner.Core.ModernizationScanJob.ModernizationScanJob_TimerJobRun(Object sender, TimerJobRunEventArgs e) in D:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\ModernizationScanJob.cs:line 190",

Error-2:
The property or field 'WebTemplate' has not been initialized. It has not been requested or the request has not been executed. It may need to be explicitly requested.","MainWebLoop","at Microsoft.SharePoint.Client.ClientObject.CheckUninitializedProperty(String propName)   at Microsoft.SharePoint.Client.Web.get_WebTemplate()   at SharePoint.Modernization.Scanner.Core.Analyzers.WebAnalyzer.Analyze(ClientContext cc) in D:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\Analyzers\WebAnalyzer.cs:line 72   at SharePoint.Modernization.Scanner.Core.ModernizationScanJob.ModernizationScanJob_TimerJobRun(Object sender, TimerJobRunEventArgs e) in D:\github\sp-dev-modernization\Tools\SharePoint.Modernization\SharePointPnP.Modernization.Scanner.Core\ModernizationScanJob.cs:line 266",

**Comment by jansenbe** [comment]
Can you share the command line you're using? Try scanning just one or more sites and see if the problem exists on all sites or just one.

**Comment by sidgdocs** [comment]
Thank you for the prompt response.

SharePoint.Modernization.Scanner.exe -v "" -a https://XXX.sharepoint.com -m WorkflowWithDetailsOnly -c $true -b $true -i <> -z gtus365.onmicrosoft.com -f "XX.pfx" -x XXX -o $true

Tried using the scan with individual sites and that works / throws the same error. Also I am trying to only scan for Workflows but seems like the tool is scanning for other components as well.

**Comment by jansenbe** [comment]
That's a weird command line, can you try with something like below:

```
.\SharePoint.Modernization.Scanner.exe -t mytenant -i e5808e8b-1111-abcd-4321-5008db04a882 -z berton
line.onmicrosoft.com  -f "C:\Modernization\BertOnlineAzureADAppOnlyDefaultPassword.pfx" -x apassword  -c -m WorkflowWithDetailsOnly -h 10 -n
```

You don't need to specify tenant admin, unless you're using vanity URL's (so url's not ending on .sharepoint.com)?

**Comment by sidgdocs** [comment]
I used the below command, because I am running the scan in batches as we have quite a few sites that we need to scan from.

.\SharePoint.Modernization.Scanner.exe -i ClientID -z domain.onmicrosoft.com -y Production -f Y:\WFScan\ModernizationScannerApp.pfx -x Password -o $true -v Y:\WFScan\Inputs\1.csv -h 30 -m WorkflowWithDetailsOnly -d $true

This is what we have noticed:
If we are running a scan on 1000 sites, some sites are errored out (ex: 100). If we run another scan with the errored out sites 100. We have seen that the tool is able to complete the scan for some of these 100 errored out sites

Any insights would be highly appreciated.

**Comment by jansenbe** [comment]
Might be throttling? If you notice errors being added to the log you could try to use Fiddler to get more details on the erroring requests

**Comment by jansenbe** [comment]
@sidgdocs : any update on this?

**Comment by jansenbe** [comment]
Closing per no response. If this is still an issue please open a new issue with the requested details.
