### ISSUE TITLE
[FEATURE] Add option to suppress interactive prompt about current version from command line

### ISSUE THREAD

**Issue by vgurus** [pnp/sp-dev-modernization#520]
**Is your feature request related to a problem? Please describe.**
When we integrate this tool with other applications, it would be great to have an option for suppressing interactive prompts for current version checks.

**Describe the solution you'd like**
If the integrating tool doesn't have the option to support interactive capability support, the scanner run won't work for the command line options passed from the other tool.

**Comment by jansenbe** [comment]
Thanks @vgurus , that's indeed a good option to include.

**Comment by vgurus** [comment]
Perfect, thanks @jansenbe! keep us posted, as soon this gets released!

**Comment by jansenbe** [comment]
@vgurus : did check the code and the the interactive version prompt only is shown when you shown the Wizard UI, when you use command line the interactive prompt is not shown, instead a simple console output is done. When you use the scanner in automation scenarios you should use configure the scanner via command line arguments. As such there's nothing to change for this request.
