### ISSUE TITLE
[BUG]Modernisation Scanner fails - invalid signature - Is this because the Graph interface has changed ?

### ISSUE THREAD

**Issue by NPrice99** [pnp/sp-dev-modernization#522]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[X ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

I expected the Modernisation Scanner to Run  without errors

#### Observed Behavior
PS C:\temp> .\SharePoint.Modernization.Scanner.exe -t mytenant -i <tenantID> -z <TenantName>.onmicrosoft.com  -f "C:\Temp\ModernizationScannerApp.pfx" -x password  -c -m WorkflowWithDetailsOnly -h 10 -n
=====================================================
Scanning is starting...26/08/2020 14:58:10
=====================================================
Error executing scan:
AADSTS700027: Client assertion contains an invalid signature. [Reason - The key was not found., Thumbprint of key used by client: '7DDB09F9E833EB98DD5861ACCBAD44FBA6E11B8D', Please visit the Azure Portal, Graph Explorer or directly use MS Graph to see configured keys for app Id 'fb63b148-11b8-42a3-8e0f-40fe76451e5d'. Review the documentation at https://docs.microsoft.com/en-us/graph/deployments to determine the corresponding service endpoint and https://docs.microsoft.com/en-us/graph/api/application-get?view=graph-rest-1.0&tabs=http to build a query request URL, such as 'https://graph.microsoft.com/beta/applications/fb63b148-11b8-42a3-8e0f-40fe76451e5d']
Trace ID: 9d6744af-6e4e-40a7-bbca-0e638f0da700
Correlation ID: 59fd52a5-3933-4009-8a26-f28fd3095b9d
Timestamp: 2020-08-26 13:58:12Z
 Press any key to continue
#### Steps to Reproduce

run this command :-  .\SharePoint.Modernization.Scanner.exe -t mytenant -i <tenantID> -z <TenantName>.onmicrosoft.com  -f "C:\Temp\ModernizationScannerApp.pfx" -x password  -c -m WorkflowWithDetailsOnly -h 10 -n

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hmm...seems like a setup issue. Can you confirm the certificate is linked to your Azure AD application? See https://docs.microsoft.com/en-us/sharepoint/dev/solution-guidance/security-apponly-azuread#setting-up-an-azure-ad-app-for-app-only-access for details on how to configure Azure AD app-only

**Comment by NPrice99** [comment]
Tried following article - failed at connect-pnponline command - Bug #2879 in PnP-PowerShell raised.  Access to -CertificatePath C:\Temp denied. (I tried other paths and they all failed)

**Comment by jansenbe** [comment]
You only need to follow the steps in the "Setting up an Azure AD app for app-only access" chapter. I've you've created the cert/pfx and have configured the Azure AD app then you can try them in the scanner

**Comment by NPrice99** [comment]
Now getting
 =====================================================
Scanning is starting...28/08/2020 13:00:26
=====================================================
Error executing scan:
The remote server returned an error: (401) Unauthorized.
 Press any key to continue

Using version 2.17

I have tried running and running as Administrator

**Comment by jansenbe** [comment]
Did you grant the proper permissions to the Azure AD app?

**Comment by jansenbe** [comment]
And did the admin consent

**Comment by NPrice99** [comment]
[cid:image002.jpg@01D67D3E.A3FA69F0]

**Comment by NPrice99** [comment]
Deleted Application Registration and recreated.  Worked this time.  Thanks for your excellent help Bert.
