### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by ManilBMO** [pnp/sp-dev-modernization#525]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

We ran Modernization Scanner on 3 different workstations:
VM Win 7 VM – /Sites/ sites csv has 250 entries
VM Win 10 VM – /Teams/ sites csv has 500 entries
My laptop – /Sites/ sites csv has 99 entries

All of them get to around 70% completion before it just seems to do nothing but retrieve search results, output results (with no change in the log file size). It’s been like that hours for all 3. When I check it it shows "Retrieving a batch of up to 500 search results". If left it running, it makes the system unresponsive.

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ x ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior
The tool should generate the result and error log

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior
All of them get to around 70% completion before it just seems to do nothing but retrieve search results, output results (with no change in the log file size). It’s been like that hours for all 3. When I check it it shows "Retrieving a batch of up to 500 search results". If left it running, it makes the system unresponsive.

_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce
Create a csv with 500 sites. Execute the tool to get workflows.
_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

**Comment by jansenbe** [comment]
@ManilBMO,

Are you using version 2.17 of the scanner? That version contains search improvements and should be less taxing on the search backend. Given a single site collection in handled in a single thread it can result in a long scan duration whenever there's a site collection with a ton of a subsites.

**Comment by ManilBMO** [comment]
We are using version 2.16.0.0

**Comment by jansenbe** [comment]
Please use version 2.17 and see if you still have issues

**Comment by jansenbe** [comment]
Closing per no feedback
