### ISSUE TITLE
[BUG] Scanner hits personal sites (/portals/personal/.....) causes 404 errors and just outputs to excel files errors. scanresults etc

### ISSUE THREAD

**Issue by NPrice99** [pnp/sp-dev-modernization#528]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ X] Modernization Scanner: something went wrong...  **Version 2.17**

#### Expected or Desired Behavior

Scanner should skip personal sites.

#### Observed Behavior
with version 2.17 

Scanner hits personal sites (url /portals/personal/.....) which causes 404 errors which seem cause scanner to timeout so sites are only scanned every minute or so.  Slows whole scan down considerably.  Finally scanner stops working (reached error limit ??) and closes

#### Steps to Reproduce

run workflow detail scan with tenant which has /portals/personal/... sites

#### Submission Guidelines

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @NPrice99 ,

The scanner by default excludes OD4B sites. Did you use the scanner via command line and provided the -o or --includeod4b option?

**Comment by NPrice99** [comment]
Hi Bert
I double clicked the exe file and filled in the boxes as appropriate - ClientID, certificate file etc.
Regards
Nigel

**Comment by NPrice99** [comment]
Hi Bert
It looks as if you need a client secret to run via the command line.
Our Tenancy still have the old version of Graph  so cannot use PowerShell command to register the app so used Plan "B" - the one you suggested I use.  Where you register the App by hand.
REgards
Nigel
