### ISSUE TITLE
[FEATURE] Ability to exclude certain site collections

### ISSUE THREAD

**Issue by NPrice99** [pnp/sp-dev-modernization#529]
**Is your feature request related to a problem? Please describe.**
SCanner gets stuck on personal sites - returns 404 error after timing out.

If I am looking for SharePoint 2010 workflows do I really need to search Teams sites ?

**Describe the solution you'd like**
An ability to exclude certain site collections eg those site collection starting with /portals/personal/ or Teams/EAnn/999

**Describe alternatives you've considered**
There is none as far as I can see

**Additional context**

**Comment by jansenbe** [comment]
You can scope the scanner to a subset of sites as mentioned here for command line usage: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq#i-only-want-to-scan-a-few-sites-can-i-do-that. For the UI mode this works as well as shown here: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner#scan-a-defined-list-of-site-collections

So in your case you can scan for /sites/*
