### ISSUE TITLE
Properties not displaying in Properties Web Part[BUG]

### ISSUE THREAD

**Issue by 14Data** [pnp/sp-dev-modernization#531]
$result = ConvertTo-PnPClientSidePage -Identity $page.FieldValues["FileLeafRef"] `
                    -PublishingPage `
                    -TargetConnection $targetConnection `
                    -PublishingTargetPageName $targetFileName `
                    -PageLayoutMapping "$($location)\$($PageLayoutMappingFile)" `
                    -Connection $sourceConnection `
                    -Overwrite `
					-TargetPageFolder "$($TargetFolder)" `
                    -TargetPageFolderOverridesDefaultFolder `
                    -SkipItemLevelPermissionCopyToClientSidePage `
                    -LogType File `
                    -CopyPageMetadata `
                    -LogSkipFlush `
                    -LogFolder $LogOutputFolder
		}

Page Mapping XML
        <Field Name="Reviewed_x0020_By" TargetFieldName="ReviewedBy" Functions="" ShowInPageProperties="true"/>
        <Field Name="InvestigationStart" TargetFieldName="StartDate" Functions="" ShowInPageProperties="true"/>
        <Field Name="InvestigationEnd" TargetFieldName="EndDate" Functions="" ShowInPageProperties="true"/>
        <Field Name="InvestigationClient" TargetFieldName="Client" Functions="" ShowInPageProperties="true"/>
        <Field Name="InvestigationSupervisor" TargetFieldName="Supervisor" Functions="" ShowInPageProperties="true"/>

The metadata column contents are being copied through, but when the Properties are displayed on the page the Data columns above are not being displayed. They are showing as blank in the Properties web part edit. 

If you manually select them they appear as expected. 

![image](https://user-images.githubusercontent.com/63935656/93143696-8635e980-f73c-11ea-95c5-1d2f31ffc498.png)

Edit Properties Web part on page and Property is blank: 

![image](https://user-images.githubusercontent.com/63935656/93143099-5cc88e00-f73b-11ea-86a9-3bb05e056075.png)

But when selected will appear on the page. 

![image](https://user-images.githubusercontent.com/63935656/93143214-98fbee80-f73b-11ea-9e64-227720ad19d0.png)

I've tried deleting all the pages and starting again, changing the column from a Date to Single Line fo Text, but all with the same result. I cannot get these fields to automatically appear in the properties web part. 

No errors reported. 
No warnings for these columns in the .md report.

**Comment by jansenbe** [comment]
@14Data : so this only applies to date columns? Can you transform a page that results in the issue, then put the modern page in maintenance mode (add ?maintenancemode=true to the url), copy the Data set of the properties web part. Once copied go in and manually fix the data web part, save the page and open it again in maintenance mode. Again copy the Data set of of the properties web part. Paste both outcomes in here, interesting to see what the differences are.

![image](https://user-images.githubusercontent.com/7451219/94114957-575cf900-fe49-11ea-919e-cea260d6fe4d.png)

**Comment by 14Data** [comment]
Hi @jansenbe, thanks for your response. Below are the 2 data extracts from a page are below. There are differences, but I don't know what they mean. Look forward to hearing your take on it and if there's a way to resolve it. 

Data Pre Update: 
[Webpate Data - PreUpdate.txt](https://github.com/pnp/sp-dev-modernization/files/5279403/Webpate.Data.-.PreUpdate.txt)

Data post Update
[Webpate Data - Updated.txt](https://github.com/pnp/sp-dev-modernization/files/5279406/Webpate.Data.-.Updated.txt)

**Comment by 14Data** [comment]
Hi @jansenbe, any ideas on what may be causing this or how to resolve it? Thanks.

**Comment by jansenbe** [comment]
@14Data , sorry but been way too busy lately...and did not yet have to time to debug this

**Comment by jansenbe** [comment]
Closing per no feedback. If this is still an issue please create a new issue in the PnP Framework repo as the page transformation bits have moved over to that repo
