### ISSUE TITLE
Rename duplicates Publishing Pages and Site Pages

### ISSUE THREAD

**Issue by albegut** [pnp/sp-dev-modernization#532]
**Is your feature request related to a problem? Please describe.**
Some source sites have two page libraries, SitePages and Pages. If there is a page with the same name in both libraries, when you modernize to SPO, only one of the two will exist. The second page that is modernized will overwrite the previous one.

**Describe the solution you'd like**
Add a new parameter that indicates if a page should have a prefix on it. Currently even if a prefix is indicated, if you are upgrading to another site collection, the prefix is omitted. 

With this solution the user is in charge of checking if the page already exists. In my case, all the publishing pages will be modernize with the same name, but when the framework try to modernize the SitePages Library, if one page already exists, It will set the prefix, "Sitepage_ ".

**Describe alternatives you've considered**

**Additional context**

**Comment by albegut** [comment]
I've done the changes in PR #533

**Comment by pkbullock** [comment]
Hi @albegut,

There is the TargetPageName option already in place for this scenario, where you can choose a target name. This is useful when converting from a heirarchical structure to flat.

**Comment by albegut** [comment]
Thanks @pkbullock . I´ve tried with prefix but I've skipped that parameter
