### ISSUE TITLE
Unable to find details about workflow last run

### ISSUE THREAD

**Issue by spo365** [pnp/sp-dev-modernization#535]
Unable to extract workflow last run details on the report, if we include these details it will be valuable in order to identify which workflow is required or not.

**Comment by Brice235i** [comment]
I agree, was going to post the same.  2 columns missing - last time SharePoint Site was modified and last time the list containing the workflow was modified would also be helpful.  We ended up using Powershell script to do this.  The Workflow last run date would be very useful.

**Comment by spo365** [comment]
@Brice235i , can you suggest how we can extract the last run date using PowerShell for 2013 workflows?

**Comment by Brice235i** [comment]
If anyone from Microsoft reviewing these issues?  I don't think it is unreasonable to update the Modernization Scanner to include a "Last Run Date"...  we have 9000 workflows... We are trying to filter obsolete instances.  We are running a powershell script to return last site modified date, but still have 2000 + workflows.  We are now attempting to run a script to return list modify dates  but running into all sorts of problems.

**Comment by Brice235i** [comment]
Sorry spo365, just saw your comment.  Will check and get back to you, but the file returned has garbled list URLs...

**Comment by Brice235i** [comment]
Hi @spo365 we got this working...  we are using list last modified and site last modified date.  See attached txt file.
[GetListProperties.txt](https://github.com/pnp/sp-dev-modernization/files/5375376/GetListProperties.txt)

**Comment by spo365** [comment]
Hi @Brice235i , Thanks for sharing the file.

**Comment by jansenbe** [comment]
@Brice235i , thanks for helping out with @spo365 's question. Closing this issue now

**Comment by spo365** [comment]
@jansenbe Do you have any recommendation on my query as we are try to extract last run details for 2013 workflow from our tenant.  As we are having around 4000 SPD 2013 workflow.
