### ISSUE TITLE
List OOTB webpart not mapping

### ISSUE THREAD

**Issue by albegut** [pnp/sp-dev-modernization#536]
#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[X] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Mapping Microsoft.SharePoint.WebPartPages.XsltListViewWebPart webpart to List OOTB webpart in SPO.

#### Observed Behavior

The framework does not find List OOTB webpart and finish the transformation omitting that webpart. 

The log file indicates the following:

29-Sep-20 17:38:56  |  Adding Web Parts to Target Page  |  Using 'List' modern web part
29-Sep-20 17:38:56  |  **Adding Web Parts to Target Page**  |  **Modern web part not found**

The problem I found is the following

1. The framework gets all of the available components at the page. - CacheManager.cs class - GetClientSideComponents Method. 
2. Then in ContentTransformator class gets the WebPart Guid by the webpart enum 
3. The Guid founded in the step 2 it's not in the available components founded in the step 1 so the mapping don`t finish correctly

#### Steps to Reproduce

Try to modernize a SP2010 page with Microsoft.SharePoint.WebPartPages.XsltListViewWebPart on it.

I did not check if there is the same problem in SharePoint online classic experience, but I think it is a problem on all platforms because It is not finding the list OOTB webpart within the available webparts

**Comment by pkbullock** [comment]
Hi Alberto,

there is a problem in SPO affecting List web parts, an key API isn’t returning modern web parts for lists. This isn’t related to modernisation or the community tooling, this is on MS side.

When this is resolved we will update this issue

Paul

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by albegut** [comment]
@pkbullock thank you for the quick response! I've delay the modernization process until the problem is solved

**Comment by pkbullock** [comment]
This problem only affects lists, all other web parts should be unaffected, if the source doesn’t contain any use of the list web part.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by pkbullock** [comment]
Hi @albegut, apparently the issue has been fixed can you test to see if your now unblocked?

**Comment by albegut** [comment]
Hi @pkbullock, yes now It's working perfectly. Thank you again for the quick response and the updates! You saved me a lot of time!
