### ISSUE TITLE
[Issue] Modernization Scanner not running to completion

### ISSUE THREAD

**Issue by doctorhummus** [pnp/sp-dev-modernization#539]
Similar to issue #519 (which has been closed) I am trying to run the scanner (version 2.17) on a site collection consisting of about 2500 sites in my tenancy to identify 2010WFs. I have used the recommended "Azure AD App-Only" option and left the scanner to run over night (I have also set the 'Sleep' setting of my machine to 'Never'). But the scanner only managed to scan about 850 of the sites, and then the scanner seems to get stuck on one site, repeatedly outputs scan results for that site in a loop, and so the scanner does not run to completion for the site collection (although having run the scanner multiple times, the scanner gets stuck on a different site each time and does not output any errors related to the stuck site).
The Errors.csv file lists only two errors (which are not the sites the scanner gets stuck on): "The operation has timed out" and "Exception from ...".
@jansenbe, Can you offer any suggestions?

(I am new to GitHub so apologies in advance if I have not reported this issue in the correct way.)

_Originally posted by @doctorhummus in https://github.com/pnp/sp-dev-modernization/issues/519#issuecomment-705508870_

**Comment by jansenbe** [comment]
@doctorhummus : the scanner will partition site collections across threads...but if a single site collection is huge, like in your case, it will be handled by a single thread. What you can try is to scan that single site collection in the most optimal situation, ideally using a Azure VM in the same region where your SharePoint tenant is hosted and see if that helps. You can also consider using the basic workflow scan option (the one without doing the analysis) as that will be faster and will identify the workflows.

Also please share the error report you got.

**Comment by doctorhummus** [comment]
@jansenbe : Thank you very much for these suggestions; I will try them out. (It might also be possible that an implicit policy in my org is putting my machine to sleep and therefore disrupting the scanner; I am looking into this.)
Here is the error report I got:
![Errors_withUrlsRemoved](https://user-images.githubusercontent.com/12052408/96251315-2b481a00-0fa8-11eb-88d9-575dbe6b0094.png)

**Comment by jansenbe** [comment]
Can this be closed?

**Comment by doctorhummus** [comment]
@jansenbe : Yes, thank you for your help.
