### ISSUE TITLE
[BUG] Modernization Scanner Not Working With MFA

### ISSUE THREAD

**Issue by robb-l** [pnp/sp-dev-modernization#542]
#### Problem Area

[ ] Modernization Scanner: When running the Modernization Scanner with the Azure AD App Only settings, we are getting a proxy error which we believe is due to MFA. We are also running it from a server, due to InfoSec policy. 

#### Expected or Desired Behavior

MFA user should able to run Modernization Scanner. 

#### Observed Behavior

When running the scanner, we are getting the following error

**Launching wizard...
=====================================================
Scanning is starting...10/2/2020 10:16:15 AM
=====================================================
Error executing scan:
The remote server returned an error: (407) Proxy Authentication Required.
 Press any key to continue**

Steps to Reproduce

- Launch Modernization Scanner
- Choose Azure AD App Only
- Select Complete Tenant
- Select Classic Workflow Usage Detailed
- Default additional scan options

**Comment by jansenbe** [comment]
Hi @robb-l : the scanner cannot be configured to use a proxy server...please run the scanner on a place that transparently can reach SharePoint Online.

**Comment by robb-l** [comment]
Thanks. I'll try that. And post my findings.

**Comment by jansenbe** [comment]
Also check my comments in #540 about MFA...MFA is fine to scan a few sites, but a tenant wide scan typically requires Azure AD App-Only (unless the tenant is really small)

**Comment by robb-l** [comment]
That's what we are currently using is Azure AD App-Only. I got the proxy error using that.

**Comment by jansenbe** [comment]
Can this be closed?

**Comment by jansenbe** [comment]
Closing per no feedback
