### ISSUE TITLE
[issue] Modernization Scanner is not working against Tenant

### ISSUE THREAD

**Issue by waqas105** [pnp/sp-dev-modernization#545]
We are still having the issue with the Scanner tool. We are getting this error even for 1 site collection scan.
"This query was not completed because the system has been configured to block such queries."

Here is the old issue link which we opened before. Issue # 519
https://github.com/pnp/sp-dev-modernization/issues/519

Support team want us to open the issue again so that they can work togeather on this.

**Comment by jansenbe** [comment]
Seems you're getting blocked on the backend, doing a workflow scan of a single site = a single search query...so are you sure there's nothing else on going that results into this? Please have the support team connect with me.

**Comment by jansenbe** [comment]
Closing this one, please have support team contact me for internal follow-up if needed.
