### ISSUE TITLE
[BUG] Community Script Editor "Not Found" and never added to transformed pages

### ISSUE THREAD

**Issue by gabrielbray** [pnp/sp-dev-modernization#546]
#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[**x**] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

Insert the modern community script editor web part, via the `<FixedWebParts>` node, during the classic publishing page transformation process. Note- I'm referencing a classic script editor web part within the above mentioned node in hopes of triggering the mapping...maybe this is the wrong approach to begin with?

#### Observed Behavior

Classic publishing page transformation completes as expected, minus the presence of the modern community script editor web part which isn't inserted into the transformed page. A warning in the generated log file indicates "Modern web part not found".

#### Steps to Reproduce

1. Classic SharePoint publishing site hosted in Microsoft 365 (source)
1. Modern communication site hosted in Microsoft 365 (destination)
1. Attached files - Convert-PublishingPages.ps1; webpartmapping.xml; pagelayoutmapping.xml. 
[webpartmapping.zip](https://github.com/pnp/sp-dev-modernization/files/5462087/webpartmapping.zip)

1. The custom page layout in question is `<PageLayout Name="EnterpriseWikiCustom" ... >`
1. Follow these [instructions](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-webparts#enabling-the-use-of-the-community-script-editor-web-part-to-be-used-during-transformation) to install the [community script editor](https://github.com/pnp/sp-dev-fx-webparts/tree/master/samples/react-script-editor) and set the required flag on the PnP PowerShell cmdlet. Once the community script editor is deployed to the app catalog (I tried both site collection and tenant), add the app to the modern communication site so it's visible in site contents.
1. Run the PowerShell script via `.\Convert-PublishingPages.ps1 -SourceSitePartUrl "<SOURCE_SITE>" -TargetSitePartUrl "<TARGET_SITE>" -PartTenant "<TENANT>"`

**Comment by jansenbe** [comment]
@gabrielbray : Did you test in a new PS shell, there's caching going on and a new shell will clear that.

**Comment by gabrielbray** [comment]
Hey @jansenbe I was looking over the documentation again and I neglected to allow custom scripting via PowerShell on the destination site. I'll follow-up if that doesn't clear up the issue.

**Comment by jansenbe** [comment]
Hi @gabrielbray : did you manage to get things working?

**Comment by gabrielbray** [comment]
Hi @jansenbe I was able to get back to it last night and it's working now. Appreciate the follow up!
