### ISSUE TITLE
[BUG]We have executed the scanner tool on whole SharePoint Online tenancy and received feedback from a user for the generated report that this scanner tool has not traced a SharePoint site collection  where SharePoint 2010 workflow is available.

### ISSUE THREAD

**Issue by Alok-sys123** [pnp/sp-dev-modernization#547]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior

_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce

_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

#### Submission Guidelines

_Delete this section after reading_

- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
- If you checked the **"Page Transformation: Error during the use of page transformation from .Net"** checkbox then please provide:
  - The exact error message you get
  - The stack trace of the error
  - The version of the **SharePointPnP.Modernization.Framework.dll** assembly

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Which version of the scanner did you use? We fixed things in the last release around workflows on list content types

**Comment by jansenbe** [comment]
Hi @Alok-sys123 : can you provide feedback about the used scanner version?

**Comment by jansenbe** [comment]
Closing per no feedback since 14 days

**Comment by Alok-sys123** [comment]
Hi Jansen

here is the scanner version which we using
2.12.0.0

**Comment by Alok-sys123** [comment]
Can you please reopen this case ?
