### ISSUE TITLE
[FEATURE Request] - Provide checksums for your releases

### ISSUE THREAD

**Issue by vgurusa** [pnp/sp-dev-modernization#549]
**Is your feature request related to a problem? Please describe.**
No, this is to ensure the downloaded SharePoint.Modernization.Scanner.exe files are safe for consumption.

**Describe the solution you'd like**
This will help with automatically downloading the latest version via code and check the hash to ensure and double check the file is safe to use.

**Describe alternatives you've considered**
Adding another text file similar to version.txt on the releases folder will help with hash checks. 

**Additional context**
Please let me know, if you need more context.

**Comment by jansenbe** [comment]
See https://github.com/pnp/sp-dev-modernization/tree/master/Tools/SharePoint.Modernization/Releases
