### ISSUE TITLE
Output to Json, XML

### ISSUE THREAD

**Issue by yumoraby** [pnp/sp-dev-modernization#552]
With CSV the data exported from the tool, is difficult to maniuplate or process in other tooling without creating a custom import mapping. Outputting to Json or XML will allow to retain and preserve schema and make it easy to port to other systems.

**Describe the solution you'd like**
Ability to export output of the tool in Json/XML

**Describe alternatives you've considered**
Currently the output has to be parsed using the defined schema, any changes in the toolset may not get picked up in the external parser which hosts the schema outside the source content.

**Additional context**

**Comment by vgurusa** [comment]
@jansenbe, as @yumoraby mentioned having the contents in JSON/XML will definitely help a lot.

**Comment by fastlaneb** [comment]
Yes, massaging CSVs into the format you want is a project unto itself. I would love to see JSON! I third this request @jansenbe @yumoraby @vgurusa

**Comment by jansenbe** [comment]
Good idea, but given my current workload I'm considering it low priority for now. The scanner is open source, I'm not against accepting a community PR that provides this capability.

**Comment by yumoraby** [comment]
@jansenbe I'll discuss this with my team tomorrow, to see who can help incorporate this feature into the toolset.

**Comment by jansenbe** [comment]
Closing per no feedback anymore
