### ISSUE TITLE
[BUG]Modernization Scanner gets stuck in a loop

### ISSUE THREAD

**Issue by kaarthik17** [pnp/sp-dev-modernization#553]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

We have a huge tenant with over 20k sites on which we are running the scanner. We have tried different options to run it (the tenant as a whole, in batches - site collections starting with the letter 'A' and so on) and it always ends up on a loop after running for a while. We have observed this problem both on a personal machine and on a Windows Server 2019. We are running the tool for only the basic workflow report (not the analysis). This issue is the same as #539.

#### Expected or Desired Behavior

The Scanner should run to completion and provide a report of all the sites with 2010 workflows.

**Comment by jansenbe** [comment]
hi @kaarthik17 : please follow our performance best practices listed here https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq#whats-the-impact-of-running-a-scan-and-how-do-i-get-the-best-performance. Also ensure you're using an app-only access method, using MFA will only work for the token lifetime, so typically for one hour.

Also ensure you're using the latest version. I you can capture a fiddler trace when the scanner gets into a loop that would be really helpful to understand what goes wrong

**Comment by jansenbe** [comment]
As there was no feedback for 3 weeks I assume the issue is resolved and will close. If you still have issues then please create a new issue and provide the requested details.
