### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by vgurusa** [pnp/sp-dev-modernization#554]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area
Unable to use the CSVFile input, if APPID and Certificate on the localmachine is used.

#### Expected or Desired Behavior
If -v option is passed for -i AppID and -w localmachine certificate thumbprint, needs to use the selected list of sites from the input CSV file.

#### Observed Behavior
Unable to get the -v input file usage when used along with AppID and LocalMachine Certificate Thumbprint -w. The behavior is completely ignores the -v input file usage.
 
#### Steps to Reproduce
Following options work:
SharePoint.Modernization.Scanner.exe -v "C:\Users\ODASPOUser\Documents\SPOModernizationScannerData\SPOScannerDefaultInput.csv" -a https://contoso-admin.sharepoint.com -d -u admin@contoso.com -p zzzzzzzzzzzzzzz
 
Following options ignores the CSV file option and scans the entire tenant:
.\SharePoint.Modernization.Scanner.exe -v "C:\Users\ODASPOUser\Documents\SPOModernizationScannerData\SPOScannerDefaultInput.csv" -t contoso -z contoso.onmicrosoft.com -i 05033a13-1ae4-4c06-9337-b8dfc3622725 -d -w "My|LocalMachine|zzzzzzzzzzzD904DD58D657CBFB3E073A1AB6774D8C"

**Comment by jansenbe** [comment]
Hi @vgurusa :
You need to remove the -t option when providing a site scope, in the working sample there's no -t, in the one that fails there is

**Comment by vgurusa** [comment]
Thanks @jansenbe! That fixed the problem, I thought that -t was required in conjunction with AppID & LocalMachineCert.
