### ISSUE TITLE
[BUG] Error running ConvertTo-PnPClientSidePage - An error ocurred processing functions

### ISSUE THREAD

**Issue by jakobnotseth** [pnp/sp-dev-modernization#555]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[x] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

No errors :-)

#### Observed Behavior

_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

Pages missing in target connection
No logs (the error here is that the Save-PnPClientSidePageConversionLog is not working
To get logs I had to run another Convert command without -LogSkipFlush
Error message in log file

## Errors during transformation

Date  |  Source Page  |  Operation  |  Message
-------------  |  -------------  |  -------------  |  -------------
19.11.2020 13:14:12  |  /nyhende/Pages/Innsida-er-oppe.aspx  |   Web Part Mapping  |  An error occurred processing functions - Parameter PersonEmail was used but is not listed as a web part property that can be used. at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ParseFunctionDefinition(String function, Property property, WebPart webPartData, WebPartEntity webPart) at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart) at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts) at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)
19.11.2020 13:14:12  |  /nyhende/Pages/Innsida-er-oppe.aspx  |   Summary  |  A critical error occurred - transformation did not complete at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ParseFunctionDefinition(String function, Property property, WebPart webPartData, WebPartEntity webPart) at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart) at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts) at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)

#### Steps to Reproduce

_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

Migrating publishing pages from SharePoint 2013 to modern pages in SharePoint Online

Using PnP PowerShell 3.16.1912.0

Script based on Contoso sample:
$target = Connect-PnPOnline https://contoso.sharepoint.com/sites/moderncommunicationsite -ReturnConnection
Connect-PnPOnline https://sharepoint2013server/sites/classicportal -CurrentCredentials
$pages = Get-PnPListItem -List Pages
foreach($page in $pages) {
ConvertTo-PnPClientSidePage -Identity $page.FieldValues["ID"] -Overwrite -TakeSourcePageName -KeepPageCreationModificationInformation -PublishingPage -TargetConnection $target -LogSkipFlush -LogVerbose -LogType File -LogFolder c:\temp
}
Save-PnPClientSidePageConversionLog

**Comment by jansenbe** [comment]
Hi @jakobnotseth ,
Please bump to the latest version of PnP PowerShell and try again, the version you're using is quite old and we don't fix older versions, so using the latest one is recommended.

**Comment by jakobnotseth** [comment]
Same bug present with latest version.

**Comment by jakobnotseth** [comment]
With version 3.26.2010.0

Date  |  Source Page  |  Operation  |  Message
-------------  |  -------------  |  -------------  |  -------------
25.11.2020 15:30:11  |  /nyhende/Pages/Innsida-er-oppe.aspx  |   Web Part Mapping  |  An error occurred processing functions - Parameter PersonEmail was used but is not listed as a web part property that can be used.    at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ParseFunctionDefinition(String function, Property property, WebPart webPartData, WebPartEntity webPart)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart)
   at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)
25.11.2020 15:30:11  |  /nyhende/Pages/Innsida-er-oppe.aspx  |   Summary  |  A critical error occurred - transformation did not complete    at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.ParseFunctionDefinition(String function, Property property, WebPart webPartData, WebPartEntity webPart)
   at SharePointPnP.Modernization.Framework.Functions.FunctionProcessor.Process(WebPart& webPartData, WebPartEntity webPart)
   at SharePointPnP.Modernization.Framework.Transform.ContentTransformator.Transform(List`1 webParts)
   at SharePointPnP.Modernization.Framework.Publishing.PublishingPageTransformator.Transform(PublishingPageTransformationInformation publishingPageTransformationInformation)

**Comment by jansenbe** [comment]
Hi @jakobnotseth ,

The errors seem to originate from transforming a Microsoft.SharePoint.Portal.WebControls.ContactFieldControl web part: can you cross check on the page that fails and check how that web part is configured? Removing the web part from the source (in case it's not needed might also be a solution for you).

**Comment by jakobnotseth** [comment]
Hi @jansenbe,
This is a custom page layout where the ContactFieldControl shows the person to contact for more information.
Cannot find it to have any special configuration though, apart from the general title/description/frametype and partimagelibrary properties.
If I could somehow get the value from this to the new page layout header in modern that would be perfect, but just getting the person webpart with the selected person would suffice. I was hoping to get this done without having to code it.
If I remove the webpart from view in the pagelayout, will I still keep the person value property in the modern page library after migration?

**Comment by jakobnotseth** [comment]
the webpart-code in question (from page-layout):
    <SharePointPortalWebControls:ContactFieldControl webpart="true" runat="server" __WebPartId="{6B3822E9-09B3-498A-B267-4854C16BCA95}"><WebPart xmlns="http://schemas.microsoft.com/WebPart/v2">
	
		<Title>Kontakt</Title>&nbsp;&nbsp; 
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <Description>Bruk denne modulen for å vise kontaktperson for siden eller området</Description>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; <FrameType>None</FrameType>
		<PartImageLarge>/_layouts/images/wp_pers.gif</PartImageLarge>
		<ID>1f6e38ab_4e39_40a0_9713_ab096d116fb9</ID>
	</WebPart></SharePointPortalWebControls:ContactFieldControl>

**Comment by jakobnotseth** [comment]
Hi @jansenbe ,

If I try to look at using webpartmapping file and custompagelayoutmapping, I get these relevant sections, not sure what to do with these though.

custompagelayoutmapping xml:
```
    <PageLayout Name="Lost_NyhendeArtikkel" AssociatedContentType="" PageLayoutTemplate="AutoDetect" PageHeader="Custom">
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="false">
        <Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingRollupImage})" />
        <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions="" />
        <Field Name="PublishingContact" HeaderProperty="Authors" Functions="ToAuthors({PublishingContact})" />
      </Header>
      <MetaData>
        <Field Name="Title" TargetFieldName="" Functions="" />
        <Field Name="Comments" TargetFieldName="" Functions="" />
        <Field Name="PublishingStartDate" TargetFieldName="" Functions="" />
        <Field Name="PublishingExpirationDate" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactEmail" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactName" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactPicture" TargetFieldName="" Functions="" />
        <Field Name="PublishingIsFurlPage" TargetFieldName="" Functions="" />
        <Field Name="ArticleStartDate" TargetFieldName="" Functions="" />
        <Field Name="Ingress" TargetFieldName="" Functions="" />
        <Field Name="Name" TargetFieldName="" Functions="" />
        <Field Name="Avdeling" TargetFieldName="" Functions="" />
        <Field Name="Tema" TargetFieldName="" Functions="" />
        <Field Name="Fagområder" TargetFieldName="" Functions="" />
        <Field Name="Bildetekst" TargetFieldName="" Functions="" />
      </MetaData>
      <WebParts>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="1">
          <Property Name="Text" Type="string" />
        </Field>
        <Field Name="PublishingPageImage" TargetWebPart="SharePointPnP.Modernization.WikiImagePart" Row="1" Column="1">
          <Property Name="ImageUrl" Type="string" Functions="ToImageUrl({PublishingPageImage})" />
          <Property Name="AlternativeText" Type="string" Functions="ToImageAltText({PublishingPageImage})" />
          <Property Name="Anchor" Type="string" Functions="ToImageAnchor({PublishingPageImage})" />
          <Property Name="Caption" Type="string" Functions="ToImageCaption({PublishingImageCaption})" />
        </Field>
      </WebParts>
      <WebPartZones>
        <WebPartZone ZoneIndex="0" ZoneId="CenterLeftColumn" Row="1" Column="1" />
        <WebPartZone ZoneIndex="0" ZoneId="CenterRightColumn" Row="1" Column="1" />
        <WebPartZone ZoneIndex="0" ZoneId="GreyRightColumn" Row="1" Column="1" />
      </WebPartZones>
      <FixedWebParts>
        <WebPart Type="Microsoft.SharePoint.Portal.WebControls.ContactFieldControl, Microsoft.SharePoint.Portal, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" Row="1" Column="1">
          <Property Name="TITLE" Type="string" Value="Kontakt" />
          <Property Name="DESCRIPTION" Type="string" Value="Bruk denne modulen for &amp;#229; vise kontaktperson for siden eller omr&amp;#229;det" />
          <Property Name="FRAMETYPE" Type="string" Value="None" />
          <Property Name="PARTIMAGELARGE" Type="string" Value="/_layouts/images/wp_pers.gif" />
          <Property Name="ID" Type="string" Value="1f6e38ab_4e39_40a0_9713_ab096d116fb9" />
        </WebPart>
      </FixedWebParts>
    </PageLayout>
```

webpartmapping xml:
```
      <WebPart Type="Microsoft.SharePoint.Portal.WebControls.ContactFieldControl, Microsoft.SharePoint.Portal, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" CrossSiteTransformationSupported="true">
        <Properties>
          <Property Name="IsIncluded" Type="bool"/>
          <Property Name="Dir" Type="string"/>
          <Property Name="PartImageSmall" Type="string"/>
          <Property Name="PartImageLarge" Type="string"/>
          <Property Name="IsIncludedFilter" Type="bool"/>
          <Property Name="CacheTimeout" Type="integer" />
          <Property Name="ContactLoginName" Type="string" Functions="LookupPerson({ContactLoginName})"/>
        </Properties>
        <Mappings Selector="UserExistsSelector({PersonEmail})">
          <Mapping Name="ValidUser" Default="true">
            <ClientSideWebPart Type="People" Order="10" JsonControlData="&#123;&quot;serverProcessedContent&quot;&#58;&#123;&quot;htmlStrings&quot;&#58;&#123;&#125;,&quot;searchablePlainTexts&quot;&#58;&#123;&quot;title&quot;&#58;&quot;{Title}&quot;,&quot;persons[0].name&quot;&#58;&quot;{PersonName}&quot;,&quot;persons[0].email&quot;&#58;&quot;{PersonEmail}&quot;&#125;,&quot;imageSources&quot;&#58;&#123;&#125;,&quot;links&quot;&#58;&#123;&#125;&#125;,&quot;dataVersion&quot;&#58;&quot;1.2&quot;,&quot;properties&quot;&#58;&#123;&quot;layout&quot;&#58;1,&quot;persons&quot;&#58;[&#123;&quot;id&quot;&#58;&quot;{PersonEmail}&quot;,&quot;upn&quot;&#58;&quot;{PersonUPN}&quot;,&quot;role&quot;&#58;&quot;{PersonRole}&quot;,&quot;department&quot;&#58;&quot;{PersonDepartment}&quot;,&quot;phone&quot;&#58;&quot;{PersonPhone}&quot;,&quot;sip&quot;&#58;&quot;{PersonSip}&quot;&#125;]&#125;&#125;"/>
          </Mapping>
          <Mapping Name="InvalidUser" Default="false">
            <ClientSideText Order="10" Text="User with ID {ContactLoginName} could not be found. Mapping to People web part was skipped."/>
          </Mapping>
        </Mappings>
      </WebPart>
```

**Comment by jansenbe** [comment]
@jakobnotseth : The file you see is a [page layout mapping file](https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-userinterface-site-pages-model-publishing) that you can use to control how publishing page content gets translated to a modern page. The reason why this is needed is because publishing pages have a flexible layout system that needs to be translated to a structured layout system on modern pages. What you can do is tell which row and column an element needs to be positioned on the modern page and the tool will figure out the needed sections and place the modern equivalents in the correct sections/columns.

In your example you see the ContactFieldControl in a the FixedWebParts section, this means that the source page layout (Lost_NyhendeArtikkel) has this web part "hard coded", meaning users creating classic publishing pages based upon this layout cannot remove the webpart. In modern pages this concept of a fixed web part does not exist, but given the web part API's do not see these fixed web parts they need to be in the pagelayout mapping if you still needed them. If you don't want the contact control you simply delete it from the FixedWebParts section.

Also don't forget to point to your updated page layout mapping file when you run the PS cmdlet.

**Comment by jakobnotseth** [comment]
Thank you @jansenbe
Removing the mapping will let me convert the pages :-)

Is it possible however to get the contact as the modern page author/editor value?
I'm currently running this command:
`ConvertTo-PnPClientSidePage -Identity $page.FieldValues["FileLeafRef"] -Overwrite -PublishingPage -TargetConnection $target -KeepPageCreationModificationInformation -WebPartMappingFile D:\migration\webpartmapping.xml -PageLayoutMapping D:\migration\custompagelayoutmapping-738a8f7e-a2c2-42e6-b078-cc3972beb4f5.xml -CopyPageMetadata -SetAuthorInPageHeader -PostAsNews
`
But it does not keep the editor/author/created/modified values, and not any metadata
Even if I try to create custom columns to keep metadata and supply the targetfieldname in mapping
Also, it is left unpublished even if I have the PostAsNews

**Comment by jansenbe** [comment]
Using `-KeepPageCreationModificationInformation` will get you the original author/date the page was created/edited (assuming the original author still exists or you've provided a mapping for it ~ see https://github.com/pnp/sp-dev-modernization/issues/557 as an issue where the users are not available anymore), so it's not taking the contact.

What you could try (did not test this) is not using the flag but controlling the mapping yourselves by updating the page layout mapping file and specify the column holding the contact as input for Author and Editor (so replace the TargetFieldName value with your source contact list item field). This however assumes the provided input is a User object...the `PublishingContact` field might the one you need...below is an XML snippet that you can try with, replace Author and Editor with PublishingContact and see what that gives

```xml
      <MetaData ShowPageProperties="true" PagePropertiesRow="1" PagePropertiesColumn="4" PagePropertiesOrder="1">
        
         ....

         <!-- Use below 4 fields to retain user created/date created, user modified/date modified will be overwritten afterwards, but you need to include them to make this "override" work -->
        <Field Name="Created" TargetFieldName="Created" Functions="" />
        <Field Name="Author" TargetFieldName="Author" Functions="" />
        <Field Name="Modified" TargetFieldName="Modified" Functions="" />
        <Field Name="Editor" TargetFieldName="Editor" Functions="" />
        
         ....

      </MetaData>

```

**Comment by jakobnotseth** [comment]
Really appreciate this @jansenbe, this got the created and modified dates in order.
Still missing all the properties though.
The users still exists so KeepPageModificationInformation should have worked
It also insists on using the target connection login for editor and author
I tried creating some custom fields to store metadata and supply the TargetFieldName as well without luck on any of the properties; PublishingStartDate, PublishingExpirationDate, PublishingContact
Also, the SetAuthorInPageHeader is not doing anything from what I can see

I might just run the migration first, then go over again with a powershell copying the list values...

**Comment by jansenbe** [comment]
Did you add additional `Field` elements for the new field. Copying of fields should just work...maybe run the transformation with verbose logging and share the log output? When you copy fields you're responsible for creating the needed fields in the target list, the tool will not do that for you. Also ensure you use similar field types.

**Comment by jakobnotseth** [comment]
Using -KeepPageCreationModificationInformation does not have any impact of the data transferred. I'm able to use a script to take the Author and Editor e-mail and write them to the list after migration, but the parameter on the powershell does not work. Mapping it individually only writes the Created and Modified fields. Other fields are ignored, even if, I did create the columns I wanted to transfer in Online first, it still did not write this to the migration.

**Comment by jansenbe** [comment]
Can you share the mapping file you're using right now?

**Comment by jakobnotseth** [comment]
```
    <PageLayout Name="Lost_NyhendeArtikkel" AssociatedContentType="" PageLayoutTemplate="AutoDetect" PageHeader="Custom">
      <Header Type="FullWidthImage" Alignment="Left" ShowPublishedDate="false">
        <Field Name="PublishingRollupImage" HeaderProperty="ImageServerRelativeUrl" Functions="ToImageUrl({PublishingRollupImage})" />
        <Field Name="ArticleByLine" HeaderProperty="TopicHeader" Functions="" />
        <Field Name="PublishingContact" HeaderProperty="Authors" Functions="ToAuthors({PublishingContact})" />
      </Header>
      <MetaData ShowPageProperties="true" PagePropertiesRow="1" PagePropertiesColumn="4" PagePropertiesOrder="1">
        <Field Name="Title" TargetFieldName="Title" Functions="" />
		<Field Name="Created" TargetFieldName="Created" Functions="" />
		<Field Name="Author" TargetFieldName="Author" Functions="" />
		<Field Name="Modified" TargetFieldName="Modified" Functions="" />
		<Field Name="Editor" TargetFieldName="Editor" Functions="" />
		<Field Name="PublishingContact" TargetFieldName="PublishingContact" Functions="" />
        <Field Name="Comments" TargetFieldName="" Functions="" />
        <Field Name="PublishingStartDate" TargetFieldName="PublishingStartDate" Functions="" />
        <Field Name="PublishingExpirationDate" TargetFieldName="PublishingExpirationDate" Functions="" />
        <Field Name="PublishingContactEmail" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactName" TargetFieldName="" Functions="" />
        <Field Name="PublishingContactPicture" TargetFieldName="" Functions="" />
        <Field Name="PublishingIsFurlPage" TargetFieldName="" Functions="" />
        <Field Name="ArticleStartDate" TargetFieldName="" Functions="" />
        <Field Name="Ingress" TargetFieldName="" Functions="" />
        <Field Name="Name" TargetFieldName="" Functions="" />
        <Field Name="Avdeling" TargetFieldName="" Functions="" />
        <Field Name="Tema" TargetFieldName="" Functions="" />
        <Field Name="Fagområder" TargetFieldName="" Functions="" />
        <Field Name="Bildetekst" TargetFieldName="" Functions="" />
      </MetaData>
      <WebParts>
        <Field Name="PublishingPageContent" TargetWebPart="SharePointPnP.Modernization.WikiTextPart" Row="1" Column="1">
          <Property Name="Text" Type="string" />
        </Field>
        <Field Name="PublishingPageImage" TargetWebPart="SharePointPnP.Modernization.WikiImagePart" Row="1" Column="1">
          <Property Name="ImageUrl" Type="string" Functions="ToImageUrl({PublishingPageImage})" />
          <Property Name="AlternativeText" Type="string" Functions="ToImageAltText({PublishingPageImage})" />
          <Property Name="Anchor" Type="string" Functions="ToImageAnchor({PublishingPageImage})" />
          <Property Name="Caption" Type="string" Functions="ToImageCaption({PublishingImageCaption})" />
        </Field>
      </WebParts>
      <WebPartZones>
        <WebPartZone ZoneIndex="0" ZoneId="CenterLeftColumn" Row="1" Column="1" />
        <WebPartZone ZoneIndex="0" ZoneId="CenterRightColumn" Row="1" Column="1" />
        <WebPartZone ZoneIndex="0" ZoneId="GreyRightColumn" Row="1" Column="1" />
      </WebPartZones>
      <!--FixedWebParts>
        <WebPart Type="Microsoft.SharePoint.Portal.WebControls.ContactFieldControl, Microsoft.SharePoint.Portal, Version=16.0.0.0, Culture=neutral, PublicKeyToken=71e9bce111e9429c" Row="1" Column="1">
          <Property Name="TITLE" Type="string" Value="Kontakt" />
          <Property Name="DESCRIPTION" Type="string" Value="Bruk denne modulen for &amp;#229; vise kontaktperson for siden eller omr&amp;#229;det" />
          <Property Name="FRAMETYPE" Type="string" Value="None" />
          <Property Name="PARTIMAGELARGE" Type="string" Value="/_layouts/images/wp_pers.gif" />
          <Property Name="ID" Type="string" Value="1f6e38ab_4e39_40a0_9713_ab096d116fb9" />
        </WebPart>
      </FixedWebParts-->
    </PageLayout>

```

**Comment by jansenbe** [comment]
Please also run this using verbose logging enabled and share the log...you either use -KeepPageCreationModificationInformation or specify the fields directly yourselves. The first approach should give the best results

**Comment by jansenbe** [comment]
What does this mean in English: There was a non critical issue during page update/publish. Returned error message: **Finner ikke den angitte brukeren <valid user>.**

**Comment by jakobnotseth** [comment]
cannot find the user

**Comment by jansenbe** [comment]
So are you sure the used user exists in SPO under that name?

**Comment by jakobnotseth** [comment]
quite sure, as it get's the author correct with the same username

**Comment by jakobnotseth** [comment]
It is also struggling to get the images across from <onpremise>/PublishingImages to <online>/siteassets/<page>. On a test site I can get it to work if I have used SPMT tool first, I'm guessing this enables some features that the conversion migth be using there, even if the target site for converted pages is the root web in the sitecollection and not the subsite it originated from. Any pointers?

**Comment by jansenbe** [comment]
About the assets: the tool only copies over images used by the image web part and by the quicklinks web part, if you're using other images (e.g. in your master page or page layout html or other web parts) then these are not copied over automatically. Can you provide an example of a case where the image is not copied?

**Comment by jansenbe** [comment]
For the publishing contact not getting set in metadata: can you update your mapping to use this: `<Field Name="PublishingContact" TargetFieldName="PublishingContact" Functions="ToAuthors({PublishingContact})" />`

Also please ensure you restart your PS session after updating the mappings as these are cached!

**Comment by jansenbe** [comment]
Closing per no feedback anymore. If you still face issues, please create a new issue in PnP Framework
