### ISSUE TITLE
[BUG] Workflows Scanner using SP Modernization Scanner Tool doesn't scan all sites from CSV

### ISSUE THREAD

**Issue by VimmiRawat** [pnp/sp-dev-modernization#558]
SharePoint Modernization Scanner tool doesn't scan all sites but doesn't throw any error either. 

Issue :
We provided a CSV with approx. 1,15,000 SharePoint sites and csv doesn't have any header. We started running the scanner , it completed without any issues and folder also got created ; but it didn't scan all the sites ; It just scanned 10,000 out if it and even if we check error file ; it shows another 2,000 records.  This has been tried twice and we see the same behavior all the times

**Comment by jansenbe** [comment]
Please make your batches smaller + check the performance best practices: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq#whats-the-impact-of-running-a-scan-and-how-do-i-get-the-best-performance. Also consider turning on the "Don't use search" option on the last page of the scan wizard to further increase performance.

**Comment by VimmiRawat** [comment]
What data will I miss on to if we turn on "turning on the "Don't use search" option" ?

**Comment by jansenbe** [comment]
You'll miss Site views and site unique visitor data. Threads: 5 x processors you have on the machine...max 30

**Comment by jansenbe** [comment]
@VimmiRawat : were you able to scan your tenant using the given guidance? If so then please close this issue

**Comment by jansenbe** [comment]
@VimmiRawat : did you manage to get the scan working with above tips?

**Comment by VimmiRawat** [comment]
Hello,

I am working on it . Scanner actually takes a lot of time even for 25k sites . It’s approx. 1 day . Is it expected ?

Regards,
Vimmi

**Comment by jansenbe** [comment]
Yes, that's abnormal. It's however better to not run too large batches...25K sites is quite large.

**Comment by VimmiRawat** [comment]
But , with company of our size ( approx, 4,80,000 SPO sites ) ; it's difficult to run the scanner with just 10 k sites as a batch as it will take more than a month to complete. Should we run the batch of 10k on 5 servers simultaneously and change the thread count ? If yes, what should we keep the thread count if we are running it on 5 servers at the same time ? If not , then ; what is the best and fastest way to run the scanner for some 5,00,000 sites ? Note : We can't wait for a month's time for this.

**Comment by jansenbe** [comment]
First step is assuring you follow the earlier mentioned performance guidance:

Please make your batches smaller + check the performance best practices: https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq#whats-the-impact-of-running-a-scan-and-how-do-i-get-the-best-performance. Also consider turning on the "Don't use search" option on the last page of the scan wizard to further increase performance.

Import is to only check the workflow scan option, definitely do not do a full scan. Also I assume you're not scanning the each user's OneDrive for Business site, makes no sense to do that with regard to workflow.

The scanner uses multi threading in a way that it splits the given set of sites over the available threads, if you've sites with a ton of sub sites these will take a very long time as they're processed by a single thread. How many sites to scan in one go really depends on your environment, but if you follow above rules you should be able to run the scan for fairly large batches of sites. You can consider running a number of scans in parallel from multiple machines, but let's first get one scan run to successfully complete.

**Comment by jansenbe** [comment]
Closing per no feedback anymore
