### ISSUE TITLE
[BUG] SharePoint Modernization Scanner tool missing workflow from SharePoint sites

### ISSUE THREAD

**Issue by ketanrana2001** [pnp/sp-dev-modernization#561]
Issue :
We have approx. 7000 SharePoint sites. Among them, we have successfully run all the sites but there are a couple of workflows missing from the sites in the report. We are using Azure ACS apps only for authentication.

Example: 
The workflow that has been created in Feb 2020 missing in all version of reports and some of the Workflow which has been created in 2019 missed in version 2.17.0.0 but it does show up in version 2.18.0.0.

Error:
We have not seen any error for missing workflow site collection or site into error reports.

**Comment by jansenbe** [comment]
2.18 fixed detection of workflows on list content types. Note that only custom workflows that have a subscription (so that are being used) are reported by the tool. Can you provide more details about the workflows you're not seeing when using version 2.18?

**Comment by jansenbe** [comment]
Closing per no response anymore
