### ISSUE TITLE
[BUG] Scanner was not able to identify active flows but only recently modified in the last 60 days

### ISSUE THREAD

**Issue by shillie** [pnp/sp-dev-modernization#565]
#### Problem Area

Modernization Scanner: The scanner reported over 42k 2010 workflows in our tenant. However a lot of the workflows show 0 count leading to believe they don't have any actions and therefore irrelevant. However, manually inspecting the workflows we are able to see that they have valid actions and are being used.

#### Expected or Desired Behavior
There are likely hundred to thousands flows that are run throughout the year; there are thousands of flows that have been running for years and never modified. We have no way to identify these via the scanner.

#### Problem Area
Action count: Thousands of flows were identified with 0 action counts, which led us to believe these were inactive, but it turns out zero action count includes flows that are OoB with no customization. 

#### Expected or Desired Behavior
0 action counts was misleading as we believed these were unable to run if there are no actions associated. Sooner explanation of this column would have helped us understand the data and potential quantity of flows.

#### Problem Area
Strange data or no data: Thousands of flows had definition names like '????? - SharePoint 2010' and '?????????? - SharePoint 2010' with no Content type, no List ID, no definition description but there was nothing to understand from this data or lackthereof to eliminate obsolete flows

#### Expected or Desired Behavior
Multiple columns should be able to provide valid data to make conclusions instead of assumptions.

**Comment by jansenbe** [comment]
@shillie : the scanner uses the workflow API's and these do not offer "usage" information so we can't provide that information in the reports. For OOB workflows we're not analyzing the workflow itself (for performance reasons), so we're not listing actions. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-reports-workflow for details on the generated report.

**Comment by jansenbe** [comment]
Closing as the question was answered.
