### ISSUE TITLE
We had executed the scanner tool manually with suggested setting.It has scanned 348 sites out of  1941 sites from the tenancy and got aborted in the middle[BUG].

### ISSUE THREAD

**Issue by Alok-sys123** [pnp/sp-dev-modernization#567]
Thank you for reporting a bug. We appreciate your feedback - to help the team to understand your needs, please complete the below template to ensure we have the necessary details to assist you. Thanks!

#### Problem Area

[ ] Page Transformation: Error during the use of page transformation from PnP PowerShell
[ ] Page Transformation: Error during the use of page transformation from .Net
[ ] Page Transformation: Page is not looking correct after transformation
[ ] Modernization Scanner: something went wrong...

#### Expected or Desired Behavior

_If you are reporting a bug, please describe the expected behavior. If you are suggesting an enhancement please
describe thoroughly the enhancement, how it can be achieved, and expected benefit._

#### Observed Behavior

_If you are reporting a bug, please describe the behavior you expected to occur when performing the action. If you are making a suggestion, you can delete this section._

#### Steps to Reproduce

_If you are reporting a bug please describe the steps to reproduce the bug in sufficient detail to allow testing. Only way to fix things properly, is to have sufficient details to reproduce it. If you are making a suggestion, you can delete this section._

#### Submission Guidelines

_Delete this section after reading_

- All suggestions or bugs are welcome, please let us know what's on your mind.
- If you checked the **"Page Transformation: Error during the use of page transformation from PnP PowerShell"** checkbox then please provide:
  - The output you see in your PowerShell session
  - The output generated by calling `Get-PnPException`
  - The PnP PowerShell version. Run `get-module -Name SharePointPnPPowerShellOnline` and copy the version info
- If you checked the **"Page Transformation: Error during the use of page transformation from .Net"** checkbox then please provide:
  - The exact error message you get
  - The stack trace of the error
  - The version of the **SharePointPnP.Modernization.Framework.dll** assembly

Thanks for your contribution! Sharing is caring.

**Comment by jansenbe** [comment]
Hi @Alok-sys123 ,

The scan run can be terminated due to various reasons (throttling, network connectivity issues,...). I would advice to split up the scan and run in an performance optimized mode. See https://docs.microsoft.com/en-us/sharepoint/dev/transform/modernize-scanner-faq for details on how to that. If you're still not able to complete a smaller scan run then please create a new issue sharing the exception that happens. Without exception details there's not much I can help with.
